export const Languages = [
  "SIMLISH",
  "TAMIL",
  "QUECHUA",
  "NAHUATL",
  "SANSKRIT",
  "BABYLONIAN",
  "ETRUSCAN",
  "MESOPOTAMIAN",
  "KOPTIC",
  "ROMANCE",
  "GERMANIC",
  "TURKISH",
  "BANTU_LIKE",
  "AFRICAN_WEST",
  "AFRICAN_HORN",
  "CN",
  "JP",
  "POLYNESIAN",
  "MONGOLIC",
  "GREEK",
  "RUSSIAN",
  "LATIN",
  "CELESTIC",
  "INFERNIC",
  "ARCANE",
  "DEEP_SPEECH",
  "GOBLINIC",
  "TECHNARCH",
  "SIRENIC",
  "OOGA_BOOGA",
  "DWARVISH",
  "HALFLING",
  "NOCTURNIC",
  "DERPTONGUE",
  "TOADISH",
  "BANANAIC",
  "LYRICIAN",
  "ANGLISH",
  "NEW_ANGLISH",
  "AMERICAN_PLACE",
  "ONOMATOPOEIC",
  "CRETAN",
  "GAULISH",
  "NORSE",
  "THAI",
  "SWAHILI",
  "ARABIC",
  "HEBREW",
] as const;

export type Language = (typeof Languages)[number];

type LanguageConfig = {
  onsets: string[];
  vowels: string[];
  codas: string[];
  codaChance: number;
  medials: string[];
  medialMorphChance: number;
  suffixes: string[];
  maxConsRun: number;
  maxVowelRun: number;
  minVowelRatio: number;
  treatYAsVowel: boolean;
  minSyllables: number;
  maxSyllables: number;
  clusterLinker: string;
  vowelLinker: string;
};

// A few reusable vowel bundles to bias families
const V_OPEN = ["a", "e", "i", "o", "u"];
const V_DIP = ["ai", "au", "ei", "ia", "io", "oa", "ue", "ui"];
const V_SOFT = ["a", "e", "i", "o", "u", "ia", "io", "ie", "ea"];
const V_SEMI = ["a", "i", "u", "aa", "ii", "uu", "ai", "au"];

export const languageConfigs: { [k: string]: LanguageConfig } = {
  SIMLISH: {
    onsets: [
      "",
      "b",
      "d",
      "g",
      "k",
      "p",
      "t",
      "m",
      "n",
      "f",
      "s",
      "v",
      "z",
      "w",
      "l",
      "r",
      "bl",
      "pl",
      "fr",
      "sn",
      "gl",
      "dr",
      "tr",
      "kl",
      "br",
      "fl",
      // classic Simlish starters
      "dag",
      "sul",
      "wub",
      "noob",
      "fraba",
      "zo",
      "plum",
      "gaba",
      "yibs",
      "laba",
    ],
    vowels: [
      "a",
      "e",
      "i",
      "o",
      "u",
      "oo",
      "ee",
      "uh",
      "ah",
      "ai",
      "oi",
      "ya",
      "wa",
    ],
    codas: [
      "b",
      "g",
      "p",
      "m",
      "n",
      "t",
      "s",
      "sh",
      "z",
      "bo",
      "doo",
      "na",
      "ba",
      "loo",
      "rah",
      "gaba",
    ],
    codaChance: 0.6,
    medials: [
      "yaba",
      "doo",
      "plum",
      "laba",
      "yibs",
      "dag",
      "fraba",
      "nooboo",
      "soola",
      "woohoo",
      "snarf",
      "wubba",
      "zo",
      "booba",
      "gooba",
      "weebs",
      "flarn",
      "snug",
      "vibsy",
    ],
    medialMorphChance: 0.5,
    suffixes: [
      "boo",
      "loo",
      "bah",
      "gah",
      "yibs",
      "so",
      "la",
      "bana",
      "weeb",
      "flarn",
      "plum",
      "vaba",
    ],
    maxConsRun: 2,
    maxVowelRun: 3,
    minVowelRatio: 0.35,
    treatYAsVowel: true,
    minSyllables: 2,
    maxSyllables: 6,
    clusterLinker: "a",
    vowelLinker: "oo",
  },
  TAMIL: {
    onsets: [
      "",
      "k",
      "t",
      "p",
      "m",
      "n",
      "ñ",
      "ng",
      "y",
      "r",
      "l",
      "v",
      "th",
      "sh",
      "ch",
      "j",
      // Dravidian flavors (ASCII approximations)
      "zh",
      "rr",
      "nn",
      "ll",
      // common name/place starts
      "tam",
      "kan",
      "kar",
      "mar",
      "sar",
      "sel",
      "ram",
      "lak",
      "mur",
      "bal",
      "pal",
      "pon",
      "mani",
    ],
    // long vowels via doubling; classic ai/au diphthongs
    vowels: ["a", "e", "i", "o", "u", "aa", "ee", "ii", "oo", "uu", "ai", "au"],
    // Mostly open syllables; Tamil keeps codas light (nasals/liquids)
    codas: ["", "m", "n", "ng", "l", "r", "rr", "zh"],
    codaChance: 0.25,
    medials: [
      // toponymic & lexical cores
      "nadu",
      "pura",
      "puram",
      "patti",
      "kudi",
      "ur",
      "oor",
      "kottai",
      "malai",
      "mala",
      "kulam",
      "thiru",
      "selva",
      "mani",
      "kannan",
      "murugan",
      "arun",
      "kumar",
      "vel",
      "amma",
    ],
    medialMorphChance: 0.45,
    suffixes: [
      "nadu",
      "puram",
      "pura",
      "patti",
      "ur",
      "oor",
      "kudi",
      "kulam",
      "malai",
      "kottai",
      "thiru",
      "nagar",
      "veli",
    ],
    // phonotactics
    maxConsRun: 2, // avoid heavy clusters; allows 'zh', 'rr'
    maxVowelRun: 3, // long vowels OK, but no vowel soup
    minVowelRatio: 0.45, // open and singable
    treatYAsVowel: false, // 'y' is a glide here
    minSyllables: 2,
    maxSyllables: 5,
    clusterLinker: "u", // epenthetic 'u' keeps CV rhythm
    vowelLinker: "y", // glide between adjacent vowels
  },
  QUECHUA: {
    onsets: [
      "a",
      "i",
      "u",
      "k",
      "q",
      "t",
      "p",
      "s",
      "m",
      "n",
      "l",
      "r",
      "y",
      "w",
      "ch",
      "kh",
      "qh",
      "ll",
      "ny",
      "hu",
      "huam",
      "hua",
      "han",
      "hak",
      "yak",
      "yac",
      "sac",
      "sak",
    ],
    // Quechua core is a–i–u; allow some e/o from Spanish-era flavor sparingly
    vowels: ["a", "i", "u", "ia", "ua", "ai", "iu", "au"],
    // Mostly open syllables; light codas show up in toponyms
    codas: ["", "n", "k", "q", "s"],
    codaChance: 0.3,
    medials: [
      "pampa",
      "marka",
      "suyu",
      "tambo",
      "pata",
      "urcu",
      "urko",
      "qucha",
      "cocha",
      "yaku",
      "sacha",
      "chakra",
      "wasi",
      "kancha",
      "suyu",
      "runa",
      "ayllu",
    ],
    medialMorphChance: 0.45,
    suffixes: [
      "suyu",
      "pampa",
      "marka",
      "pata",
      "tambo",
      "wasi",
      "qucha",
      "cocha",
      "yaku",
      "sacha",
      "kancha",
      "runa",
    ],
    // phonotactics
    maxConsRun: 2, // Quechuan avoids heavy clusters
    maxVowelRun: 2, // keeps the CV rhythm tight
    minVowelRatio: 0.4, // open, singable
    treatYAsVowel: false, // y ~ glide/consonant
    minSyllables: 2,
    maxSyllables: 5,
    clusterLinker: "i", // epenthetic i is common
    vowelLinker: "y", // glide between adjacent vowels
  },
  NAHUATL: {
    onsets: [
      "a",
      "e",
      "i",
      "o",
      "ka",
      "ke",
      "ki",
      "ko",
      "kwa",
      "kwe",
      "kwi",
      "kwo",
      "ma",
      "me",
      "mi",
      "mo",
      "na",
      "ne",
      "ni",
      "no",
      "pa",
      "pe",
      "pi",
      "po",
      "ta",
      "te",
      "ti",
      "to",
      "tl",
      "tla",
      "tle",
      "tli",
      "tlo",
      "ya",
      "ye",
      "yi",
      "yo",
      "hua",
      "hue",
      "hui",
      "huo",
      "cu",
      "cue",
      "cui",
      "co",
      "qui",
      "que",
      "za",
      "ze",
      "zi",
      "zo",
    ],
    vowels: ["a", "e", "i", "o", "u", "ia", "ua", "ui", "ei", "oa"],
    codas: [
      "n",
      "t",
      "l",
      "tl",
      "lli",
      "pan",
      "can",
      "yan",
      "hua",
      "zin",
      "te",
      "co",
    ],
    codaChance: 0.65,
    medials: [
      "tlan",
      "hua",
      "co",
      "can",
      "pan",
      "te",
      "xi",
      "zo",
      "na",
      "ya",
      "otl",
      "atl",
      "mix",
      "tzon",
      "pilli",
      "mecatl",
      "quetz",
      "chol",
      "tonal",
    ],
    medialMorphChance: 0.5,
    suffixes: [
      "tlan",
      "tlal",
      "co",
      "can",
      "pan",
      "yan",
      "tepetl",
      "huacan",
      "miztli",
      "quetzal",
      "tonal",
      "nahuac",
      "zuma",
      "tlani",
      "teotl",
    ],
    maxConsRun: 2, // Nahuatl avoids huge clusters
    maxVowelRun: 2,
    minVowelRatio: 0.35,
    treatYAsVowel: true,
    minSyllables: 2,
    maxSyllables: 4,
    clusterLinker: "a", // common epenthesis vowel
    vowelLinker: "h", // soft breath between vowels
  },
  SANSKRIT: {
    onsets: [
      "a",
      "i",
      "u",
      "e",
      "o",
      "ka",
      "kha",
      "ga",
      "gha",
      "cha",
      "ch",
      "ja",
      "jha",
      "ta",
      "tha",
      "da",
      "dha",
      "pa",
      "pha",
      "ba",
      "bha",
      "ma",
      "na",
      "ra",
      "la",
      "sa",
      "sha",
      "sri",
      "va",
      "ya",
      "ha",
      "tra",
      "dra",
      "pra",
      "bra",
      "kra",
      "gra",
      "pla",
      "gla",
      "kla",
      "ksha",
      "jna",
    ],
    vowels: ["a", "i", "u", "e", "o", "aa", "ii", "uu", "ai", "au", "ri", "ru"],
    codas: ["", "m", "n", "s", "h", "r", "ya", "ra", "na"],
    codaChance: 0.4,
    medials: [
      "indra",
      "deva",
      "raja",
      "pura",
      "nagara",
      "giri",
      "sar",
      "vara",
      "varta",
      "kuta",
      "kaya",
      "maya",
      "yoga",
      "sena",
      "kashi",
      "tirtha",
      "ksetra",
      "alaya",
      "bhumi",
      "ratna",
    ],
    medialMorphChance: 0.5,
    suffixes: [
      "pura",
      "nagara",
      "sthana",
      "desa",
      "loka",
      "varsha",
      "ksetra",
      "alaya",
      "ashrama",
      "mandir",
      "grama",
    ],
    // phonotactics
    maxConsRun: 3, // allow clusters like 'ksh', 'str'
    maxVowelRun: 2,
    minVowelRatio: 0.33,
    treatYAsVowel: false, // 'y' behaves as a glide/consonant
    minSyllables: 2,
    maxSyllables: 5,
    clusterLinker: "a", // Sanskrit loves schwa/‘a’ epenthesis
    vowelLinker: "y", // glide between vowels (aya/iya/…)
  },
  BABYLONIAN: {
    onsets: [
      "ab",
      "ak",
      "am",
      "an",
      "ar",
      "as",
      "at",
      "ba",
      "bal",
      "bar",
      "bel",
      "bil",
      "da",
      "dar",
      "du",
      "en",
      "es",
      "er",
      "ga",
      "gal",
      "gur",
      "ha",
      "hal",
      "ka",
      "kar",
      "ku",
      "la",
      "lam",
      "ma",
      "mar",
      "mu",
      "na",
      "nam",
      "nar",
      "ni",
      "nu",
      "pa",
      "rab",
      "ram",
      "sar",
      "sha",
      "sham",
      "sin",
      "sum",
      "tar",
      "tam",
      "ur",
      "ush",
      "zal",
      "zim",
    ],
    vowels: ["a", "e", "i", "u", "ia", "ai", "ua", "aa", "ei"],
    codas: [
      "n",
      "m",
      "r",
      "l",
      "sh",
      "t",
      "k",
      "s",
      "b",
      "g",
      "z",
      "th",
      "um",
      "il",
    ],
    codaChance: 0.7,
    medials: [
      "ash",
      "esh",
      "ish",
      "ush",
      "nin",
      "bel",
      "mar",
      "lam",
      "tam",
      "ur",
      "an",
      "en",
      "sin",
      "ram",
      "sam",
      "bal",
      "nam",
      "gal",
      "dur",
      "zur",
      "esh",
      "mur",
      "lum",
      "sum",
    ],
    medialMorphChance: 0.55,
    suffixes: [
      "ra",
      "ur",
      "esh",
      "an",
      "en",
      "il",
      "im",
      "um",
      "nin",
      "lam",
      "tam",
      "bel",
      "duk",
      "zum",
      "mar",
    ],
    maxConsRun: 3,
    maxVowelRun: 2,
    minVowelRatio: 0.28,
    treatYAsVowel: false,
    minSyllables: 2,
    maxSyllables: 5,
    clusterLinker: "u",
    vowelLinker: "r",
  },
  ETRUSCAN: {
    onsets: [
      "a",
      "e",
      "i",
      "o",
      "u",
      "th",
      "ph",
      "ch",
      "cl",
      "fl",
      "tr",
      "vl",
      "ml",
      "pl",
      "vel",
      "lar",
      "tur",
      "uni",
      "ais",
      "seth",
      "arn",
      "mar",
    ],
    vowels: ["a", "e", "i", "o", "u", "ae", "ai", "ei", "ia", "io", "ui"],
    codas: ["s", "n", "r", "th", "ch", "m", "l", "t", "sna", "ni", "ce"],
    codaChance: 0.55,
    medials: [
      "lar",
      "thur",
      "vel",
      "uni",
      "tur",
      "seth",
      "arn",
      "mar",
      "avl",
      "clan",
      "than",
      "ath",
      "aci",
      "nes",
    ],
    medialMorphChance: 0.5,
    suffixes: ["th", "ce", "na", "le", "ra", "chi", "sna", "ni", "thil", "ate"],
    maxConsRun: 2,
    maxVowelRun: 2,
    minVowelRatio: 0.35,
    treatYAsVowel: true,
    minSyllables: 2,
    maxSyllables: 5,
    clusterLinker: "a",
    vowelLinker: "l",
  },
  MESOPOTAMIAN: {
    onsets: [
      "an",
      "en",
      "in",
      "un",
      "ur",
      "ni",
      "ku",
      "lu",
      "mu",
      "nu",
      "su",
      "ba",
      "da",
      "ga",
      "ka",
      "ra",
      "na",
      "pa",
      "ti",
      "zi",
      "ash",
      "esh",
      "ish",
      "ush",
      "nin",
      "ding",
      "lil",
      "bel",
      "mar",
      "nab",
      "gil",
      "is",
      "tam",
      "sam",
    ],
    vowels: ["a", "e", "i", "u", "ia", "ai", "ua", "ei", "aa", "uu"],
    codas: ["n", "m", "r", "l", "sh", "t", "k", "s", "b", "g", "z", "th", "ur"],
    codaChance: 0.65,
    medials: [
      "lil",
      "bel",
      "ash",
      "esh",
      "nin",
      "ur",
      "ki",
      "zu",
      "ra",
      "an",
      "utu",
      "sin",
      "tam",
      "nam",
      "gil",
      "lam",
      "esh",
      "dum",
      "ish",
      "mur",
      "sum",
      "zur",
      "mal",
      "kal",
    ],
    medialMorphChance: 0.55,
    suffixes: [
      "ra",
      "ur",
      "esh",
      "ish",
      "an",
      "en",
      "il",
      "im",
      "um",
      "nin",
      "lam",
      "tam",
      "bel",
      "duk",
      "zum",
      "mar",
    ],
    maxConsRun: 3,
    maxVowelRun: 2,
    minVowelRatio: 0.28,
    treatYAsVowel: false,
    minSyllables: 2,
    maxSyllables: 5,
    clusterLinker: "u",
    vowelLinker: "r",
  },
  KOPTIC: {
    onsets: [
      "an",
      "am",
      "ba",
      "ka",
      "ra",
      "sa",
      "ma",
      "na",
      "pa",
      "te",
      "ne",
      "mer",
      "ket",
      "sen",
      "neb",
      "hotep",
      "set",
      "ankh",
      "khem",
      "tep",
      "ram",
      "mut",
      "thot",
      "ptah",
    ],
    vowels: ["a", "e", "i", "o", "u", "aa", "ia", "ai", "au", "ei", "ua", "oa"],
    codas: [
      "t",
      "k",
      "m",
      "n",
      "r",
      "s",
      "h",
      "p",
      "kh",
      "sh",
      "pt",
      "ph",
      "th",
      "sek",
    ],
    codaChance: 0.6,
    medials: [
      "ra",
      "maat",
      "seth",
      "amon",
      "neter",
      "ankh",
      "hotep",
      "nef",
      "sek",
      "tep",
      "amonr",
      "phar",
      "mut",
      "sob",
      "khaf",
      "nefer",
      "ram",
      "akh",
      "tem",
      "sen",
    ],
    medialMorphChance: 0.55,
    suffixes: [
      "hotep",
      "ankh",
      "ra",
      "tep",
      "mut",
      "set",
      "amen",
      "nef",
      "sek",
      "ka",
      "ur",
      "het",
      "shut",
    ],
    maxConsRun: 2,
    maxVowelRun: 2,
    minVowelRatio: 0.33,
    treatYAsVowel: false,
    minSyllables: 2,
    maxSyllables: 6,
    clusterLinker: "e",
    vowelLinker: "n",
  },
  ROMANCE: {
    onsets: [
      "b",
      "c",
      "d",
      "f",
      "g",
      "l",
      "m",
      "n",
      "p",
      "r",
      "s",
      "t",
      "br",
      "cr",
      "dr",
      "fl",
      "gl",
      "gr",
      "pl",
      "pr",
      "tr",
      "vr",
      "ch",
      "cl",
      "fr",
      "bl",
      "ros",
      "san",
    ],
    vowels: [...V_SOFT, "ue", "eo", "ia", "io", "ai", "au"],
    codas: ["n", "r", "s", "l", "m", "t", "z"],
    codaChance: 0.5,
    medials: [
      "del",
      "dor",
      "ver",
      "mar",
      "val",
      "lor",
      "ria",
      "lia",
      "mia",
      "fort",
      "bell",
      "ciel",
      "rosa",
      "vino",
      "fior",
      "cast",
      "mont",
      "sant",
      "riv",
      "cor",
    ],
    medialMorphChance: 0.45,
    suffixes: [
      "ia",
      "aria",
      "esia",
      "orio",
      "ano",
      "ino",
      "etta",
      "enza",
      "ella",
      "esco",
      "ura",
      "ito",
      "a",
      "o",
      "es",
    ],
    maxConsRun: 2,
    maxVowelRun: 3,
    minVowelRatio: 0.35,
    treatYAsVowel: true,
    minSyllables: 2,
    maxSyllables: 5,
    clusterLinker: "e",
    vowelLinker: "l",
  },
  GERMANIC: {
    onsets: [
      "b",
      "d",
      "f",
      "g",
      "h",
      "k",
      "l",
      "m",
      "n",
      "p",
      "r",
      "s",
      "t",
      "w",
      "th",
      "br",
      "cr",
      "dr",
      "fr",
      "gr",
      "kr",
      "pr",
      "tr",
      "st",
      "sk",
      "sp",
      "sn",
      "sm",
      "sw",
      "sch",
    ],
    vowels: [...V_OPEN, ...V_DIP, "au", "ei", "ie", "oo"],
    codas: [
      "nd",
      "rt",
      "rm",
      "rg",
      "lf",
      "rk",
      "lt",
      "st",
      "sk",
      "n",
      "r",
      "m",
      "l",
      "k",
      "t",
    ],
    codaChance: 0.7,
    medials: [
      "wald",
      "heim",
      "mark",
      "gard",
      "dorf",
      "stein",
      "burg",
      "holt",
      "feld",
      "lund",
      "brun",
      "thal",
      "hart",
      "grim",
    ],
    medialMorphChance: 0.35,
    suffixes: [
      "land",
      "heim",
      "berg",
      "burg",
      "holt",
      "feld",
      "stein",
      "fjord",
      "mere",
      "vale",
    ],
    maxConsRun: 3,
    maxVowelRun: 2,
    minVowelRatio: 0.25,
    treatYAsVowel: true,
    minSyllables: 2,
    maxSyllables: 5,
    clusterLinker: "e",
    vowelLinker: "n",
  },
  TURKISH: {
    onsets: [
      "a",
      "e",
      "i",
      "o",
      "u",
      "b",
      "c",
      "ch",
      "d",
      "f",
      "g",
      "h",
      "j",
      "k",
      "l",
      "m",
      "n",
      "p",
      "r",
      "s",
      "sh",
      "t",
      "v",
      "y",
      "z",
      "bl",
      "br",
      "kl",
      "kr",
      "pl",
      "pr",
      "tr",
      "dr",
      "gl",
      "gr",
    ],
    vowels: ["a", "e", "i", "o", "u", "ai", "ei", "oi", "au", "ia", "io", "ua"],
    codas: [
      "k",
      "n",
      "r",
      "l",
      "m",
      "s",
      "t",
      "an",
      "ar",
      "er",
      "in",
      "ir",
      "un",
      "ur",
      "lar",
      "ler",
      "tan",
      "tor",
      "tur",
      "kan",
    ],
    codaChance: 0.65,
    medials: [
      "kara",
      "gol",
      "dag",
      "tash",
      "bahar",
      "deniz",
      "su",
      "yer",
      "chay",
      "ova",
      "cham",
      "gok",
      "tash",
      "saray",
      "kapi",
      "hisar",
      "koy",
      "shehir",
      "ay",
      "chinar",
      "yel",
      "kuz",
      "yildiz",
      "dere",
      "ishik",
      "toprak",
    ],
    medialMorphChance: 0.6,
    suffixes: [
      "koy",
      "shehir",
      "ova",
      "golu",
      "hisar",
      "kent",
      "yaka",
      "li",
      "lu",
      "lik",
      "luk",
      "pinar",
      "dere",
      "tash",
      "chay",
      "su",
      "han",
      "kapi",
      "yer",
      "yurt",
    ],
    maxConsRun: 2,
    maxVowelRun: 2,
    minVowelRatio: 0.4,
    treatYAsVowel: false,
    minSyllables: 2,
    maxSyllables: 4,
    clusterLinker: "a",
    vowelLinker: "y",
  },
  SEMITIC: {
    onsets: [
      "al",
      "ar",
      "as",
      "bal",
      "dar",
      "qal",
      "mal",
      "ram",
      "sam",
      "zar",
      "bar",
      "sar",
      "ham",
      "has",
      "kar",
      "lam",
      "nah",
      "tas",
      "rah",
      "fa",
      "za",
    ],
    vowels: [...V_SEMI, "aa", "ai", "ei", "ia"],
    codas: ["n", "m", "r", "l", "s", "h", "t", "d"],
    codaChance: 0.55,
    medials: [
      "har",
      "sar",
      "ram",
      "bar",
      "rah",
      "nah",
      "far",
      "kal",
      "tal",
      "mir",
      "zah",
      "mar",
    ],
    medialMorphChance: 0.55,
    suffixes: ["ia", "aya", "iyya", "ah", "an", "un", "iel", "em", "een"],
    maxConsRun: 2,
    maxVowelRun: 3,
    minVowelRatio: 0.32,
    treatYAsVowel: false,
    minSyllables: 2,
    maxSyllables: 5,
    clusterLinker: "a",
    vowelLinker: "y",
  },
  BANTU_LIKE: {
    onsets: [
      "ba",
      "ka",
      "ma",
      "na",
      "sa",
      "la",
      "ga",
      "pa",
      "ra",
      "cha",
      "tsa",
      "kwa",
      "gwa",
      "mwa",
      "nla",
      "mba",
      "nda",
      "nga",
      "ha",
    ],
    vowels: ["a", "e", "i", "o", "u", "a", "a", "i", "o", "u"],
    codas: [""],
    codaChance: 0.05,
    medials: ["na", "ma", "ka", "ra", "ba", "la"],
    medialMorphChance: 0.25,
    suffixes: ["ia", "ana", "uma", "ela", "olo"],
    maxConsRun: 1,
    maxVowelRun: 4,
    minVowelRatio: 0.5,
    treatYAsVowel: true,
    minSyllables: 2,
    maxSyllables: 6,
    clusterLinker: "",
    vowelLinker: "n",
  },
  AFRICAN_WEST: {
    onsets: [
      "a",
      "ba",
      "da",
      "ka",
      "fa",
      "ga",
      "la",
      "ma",
      "na",
      "oba",
      "ola",
      "ade",
      "kw",
      "gb",
      "ch",
      "ny",
      "eke",
      "ife",
      "olu",
      "ayo",
      "tunde",
      "chi",
      "obi",
    ],
    vowels: ["a", "e", "i", "o", "u", "ai", "oa", "ie", "ua", "aa", "ei"],
    codas: ["n", "m", "wa", "ra", "ya", "ba", "", "do"],
    codaChance: 0.4,
    medials: [
      "loba",
      "femi",
      "kwe",
      "tunde",
      "chukwu",
      "nwa",
      "kofi",
      "yemi",
      "sade",
      "dapo",
      "bisi",
      "tola",
      "ayo",
      "seun",
    ],
    medialMorphChance: 0.5,
    suffixes: ["la", "ba", "ra", "ni", "do", "ma", "si", "ye", "wa", "le"],
    maxConsRun: 2,
    maxVowelRun: 4,
    minVowelRatio: 0.45,
    treatYAsVowel: true,
    minSyllables: 2,
    maxSyllables: 6,
    clusterLinker: "a",
    vowelLinker: "n",
  },
  AFRICAN_HORN: {
    onsets: [
      "ab",
      "ad",
      "as",
      "ba",
      "da",
      "ha",
      "ka",
      "ma",
      "na",
      "sa",
      "ra",
      "ta",
      "gez",
      "tes",
      "hab",
      "sel",
      "mer",
      "zer",
      "yon",
      "lem",
      "kid",
      "sen",
      "tek",
      "geb",
      "yor",
    ],
    vowels: ["a", "e", "i", "o", "u", "aa", "ee", "ei", "ia", "ua", "io"],
    codas: ["s", "m", "n", "l", "t", "k", "r", "", "h"],
    codaChance: 0.5,
    medials: [
      "sel",
      "geb",
      "tek",
      "yon",
      "hab",
      "mar",
      "zer",
      "wold",
      "yas",
      "lem",
      "kid",
      "ber",
      "sen",
      "hak",
    ],
    medialMorphChance: 0.55,
    suffixes: ["el", "es", "os", "on", "u", "en", "em", "et", "ah"],
    maxConsRun: 2,
    maxVowelRun: 3,
    minVowelRatio: 0.4,
    treatYAsVowel: true,
    minSyllables: 2,
    maxSyllables: 6,
    clusterLinker: "e",
    vowelLinker: "n",
  },
  CN: {
    onsets: [
      "b",
      "p",
      "m",
      "f",
      "d",
      "t",
      "n",
      "l",
      "g",
      "k",
      "h",
      "zh",
      "ch",
      "sh",
      "r",
      "z",
      "c",
      "s",
      "j",
      "q",
      "x",
      "y",
      "w",
      "gu",
      "ku",
      "hu",
      "lu",
      "mu",
      "xi",
      "liang",
      "long",
    ],
    vowels: [
      "a",
      "o",
      "e",
      "i",
      "u",
      "ü",
      "ai",
      "ei",
      "ao",
      "ou",
      "ia",
      "ie",
      "iao",
      "iu",
      "ua",
      "uo",
      "ui",
      "üe",
      "er",
      "an",
      "ang",
      "en",
      "eng",
      "ong",
    ],
    codas: ["n", "ng", "", "r"],
    codaChance: 0.45,
    medials: [
      "shan",
      "jiang",
      "he",
      "hu",
      "zhou",
      "dao",
      "lin",
      "yang",
      "qing",
      "jing",
      "guo",
      "cheng",
      "hai",
      "feng",
      "liang",
      "hua",
      "long",
      "yun",
      "xing",
      "mei",
      "xi",
      "tai",
      "hong",
      "lan",
      "tian",
      "bao",
    ],
    medialMorphChance: 0.4,
    suffixes: [
      "shan",
      "dao",
      "zhou",
      "guo",
      "cheng",
      "men",
      "hai",
      "yuan",
      "jing",
      "tan",
      "he",
      "lin",
      "feng",
      "yun",
      "xiang",
    ],
    maxConsRun: 2,
    maxVowelRun: 3,
    minVowelRatio: 0.3,
    treatYAsVowel: false,
    minSyllables: 2,
    maxSyllables: 5,
    clusterLinker: "e",
    vowelLinker: "n",
  },
  JP: {
    onsets: [
      "k",
      "s",
      "t",
      "n",
      "h",
      "m",
      "y",
      "r",
      "w",
      "g",
      "z",
      "d",
      "b",
      "p",
      "ky",
      "sh",
      "ch",
      "ny",
      "hy",
      "my",
      "ry",
      "gy",
      "j",
      "py",
      "tak",
      "min",
      "har",
      "kaz",
      "yam",
      "mor",
      "sug",
      "tos",
      "ken",
      "rin",
      "aki",
      "yosh",
      "nao",
    ],
    vowels: ["a", "i", "u", "e", "o", "ai", "ou", "ei"],
    codas: ["", "n"],
    codaChance: 0.4,
    medials: [
      "mori",
      "yama",
      "kawa",
      "gawa",
      "shima",
      "jima",
      "saka",
      "hara",
      "tani",
      "naka",
      "oka",
      "zawa",
      "miya",
      "sugi",
      "tora",
      "fune",
      "nori",
      "kaze",
      "seki",
      "matsu",
      "hana",
      "take",
      "ishi",
      "sora",
      "minato",
      "arai",
      "kuni",
      "aki",
      "nobu",
      "hiko",
    ],
    medialMorphChance: 0.4,
    suffixes: [
      "to",
      "ken",
      "do",
      "fu",
      "shi",
      "mura",
      "saki",
      "hama",
      "gane",
      "no",
      "ya",
      "zaki",
      "moto",
      "dai",
      "zawa",
      "sawa",
      "gawa",
      "jima",
      "sei",
    ],
    maxConsRun: 2,
    maxVowelRun: 3,
    minVowelRatio: 0.35,
    treatYAsVowel: false,
    minSyllables: 2,
    maxSyllables: 5,
    clusterLinker: "u",
    vowelLinker: "n",
  },
  POLYNESIAN: {
    onsets: [
      "",
      "h",
      "k",
      "l",
      "m",
      "n",
      "p",
      "r",
      "t",
      "w",
      "f",
      "v",
      "wh",
      "ng",
    ],
    vowels: ["a", "e", "i", "o", "u"],
    codas: ["", "’", "ʻ"],
    codaChance: 0.18,
    medials: [
      "moa",
      "moana",
      "rangi",
      "tonga",
      "tai",
      "wai",
      "puna",
      "tapu",
      "mana",
      "ariki",
      "tiki",
      "honu",
      "pua",
      "mata",
      "ika",
      "nui",
      "loa",
      "roa",
      "hale",
      "fale",
      "mauna",
      "nalu",
      "kai",
      "kea",
      "waiu",
      "pala",
      "koro",
    ],
    medialMorphChance: 0.38,
    suffixes: [
      "nui",
      "roa",
      "loa",
      "rangi",
      "moana",
      "tonga",
      "tai",
      "puna",
      "motu",
      "kai",
      "tahi",
      "ora",
      "kiri",
    ],
    maxConsRun: 1,
    maxVowelRun: 4,
    minVowelRatio: 0.5,
    treatYAsVowel: false,
    minSyllables: 2,
    maxSyllables: 6,
    clusterLinker: "",
    vowelLinker: "n",
  },
  MONGOLIC: {
    onsets: [
      "ba",
      "bo",
      "bu",
      "ta",
      "to",
      "tu",
      "ga",
      "go",
      "gu",
      "da",
      "do",
      "du",
      "kha",
      "kh",
      "qa",
      "qar",
      "gur",
      "dar",
      "bor",
      "nar",
      "sar",
      "bat",
      "alt",
      "bogd",
      "sukh",
      "ul",
      "tur",
      "tor",
      "ur",
      "ar",
      "or",
    ],
    vowels: [
      "a",
      "e",
      "i",
      "o",
      "u",
      "aa",
      "ee",
      "ii",
      "oo",
      "uu",
      "ai",
      "oi",
      "ua",
    ],
    codas: ["n", "r", "g", "t", "s", "k", ""],
    codaChance: 0.55,
    medials: [
      "bator",
      "baatar",
      "dorj",
      "suren",
      "erdene",
      "tungal",
      "bayar",
      "bold",
      "gan",
      "khaan",
      "ger",
      "gol",
      "dalai",
      "del",
      "uur",
      "saihan",
      "altai",
    ],
    medialMorphChance: 0.5,
    suffixes: [
      "bator",
      "baatar",
      "gur",
      "tengri",
      "dalai",
      "khaan",
      "khun",
      "gol",
      "ger",
    ],
    maxConsRun: 2,
    maxVowelRun: 2,
    minVowelRatio: 0.34,
    treatYAsVowel: false,
    minSyllables: 2,
    maxSyllables: 6,
    clusterLinker: "e",
    vowelLinker: "n",
  },
  GREEK: {
    onsets: [
      "a",
      "e",
      "i",
      "o",
      "u",
      "k",
      "p",
      "t",
      "n",
      "m",
      "l",
      "r",
      "s",
      "d",
      "b",
      "g",
      "x",
      "ch",
      "ph",
      "th",
      "ps",
      "kr",
      "br",
      "tr",
    ],
    vowels: ["a", "e", "i", "o", "u", "ai", "ei", "oi", "ou", "au", "ia", "io"],
    codas: ["s", "n", "r", "m", "l", "os", "on", "as", "is"],
    codaChance: 0.55,
    medials: [
      "polis",
      "agora",
      "acro",
      "therm",
      "geo",
      "philo",
      "neo",
      "arch",
      "dora",
      "kastro",
      "nik",
      "dios",
    ],
    medialMorphChance: 0.45,
    suffixes: ["os", "on", "ia", "is", "as", "ikon", "ides"],
    maxConsRun: 2,
    maxVowelRun: 2,
    minVowelRatio: 0.33,
    treatYAsVowel: false,
    minSyllables: 2,
    maxSyllables: 5,
    clusterLinker: "o",
    vowelLinker: "n",
  },
  RUSSIAN: {
    onsets: [
      "b",
      "v",
      "g",
      "d",
      "z",
      "k",
      "l",
      "m",
      "n",
      "p",
      "r",
      "s",
      "t",
      "br",
      "bl",
      "kr",
      "kl",
      "pr",
      "pl",
      "gr",
      "gl",
      "dr",
      "dl",
      "st",
      "sk",
      "str",
      "sl",
      "sm",
      "sn",
      "zh",
      "ch",
      "sh",
      "ts",
      "tz",
      "tr",
    ],
    vowels: ["a", "e", "i", "o", "u", "ya", "yo", "yu", "ia", "ie", "io", "oi"],
    codas: [
      "v",
      "n",
      "r",
      "sk",
      "st",
      "ch",
      "sh",
      "k",
      "vich",
      "nik",
      "nov",
      "mir",
      "gor",
      "grad",
      "lin",
      "ev",
      "ov",
      "in",
      "en",
    ],
    codaChance: 0.75,
    medials: [
      "slav",
      "grad",
      "mir",
      "bor",
      "dov",
      "vol",
      "krav",
      "mirs",
      "krov",
      "bel",
      "ost",
      "tar",
      "grom",
      "step",
      "vel",
      "ser",
      "zar",
    ],
    medialMorphChance: 0.55,
    suffixes: [
      "ov",
      "in",
      "sky",
      "ska",
      "ovich",
      "ev",
      "enko",
      "grad",
      "mir",
      "ovka",
      "ovna",
      "aya",
    ],
    maxConsRun: 3,
    maxVowelRun: 2,
    minVowelRatio: 0.25,
    treatYAsVowel: false,
    minSyllables: 2,
    maxSyllables: 5,
    clusterLinker: "e",
    vowelLinker: "y",
  },
  LATIN: {
    onsets: [
      "a",
      "e",
      "i",
      "o",
      "u",
      "b",
      "c",
      "d",
      "f",
      "g",
      "l",
      "m",
      "n",
      "p",
      "r",
      "s",
      "t",
      "v",
      "cl",
      "fl",
      "gl",
      "pr",
      "tr",
      "cr",
      "pl",
      "fr",
      "gr",
      "dr",
      "qu",
      "sc",
      "sp",
      "st",
      "ct",
      "ph",
    ],
    vowels: [
      "a",
      "e",
      "i",
      "o",
      "u",
      "ae",
      "oe",
      "au",
      "ia",
      "io",
      "ua",
      "uo",
      "eu",
    ],
    codas: ["s", "n", "r", "m", "t", "l", "us", "um", "a", "is", "os"],
    codaChance: 0.58,
    medials: [
      "dom",
      "val",
      "magn",
      "clar",
      "fort",
      "sanct",
      "imper",
      "aure",
      "vit",
      "cel",
      "luc",
      "reg",
      "mart",
      "pax",
      "bell",
      "civ",
      "jur",
      "templ",
      "script",
      "capit",
      "aug",
      "pont",
      "caes",
      "roman",
    ],
    medialMorphChance: 0.52,
    suffixes: [
      "us",
      "um",
      "a",
      "or",
      "is",
      "ianus",
      "ensis",
      "atus",
      "itas",
      "orium",
      "arium",
      "alis",
      "ivus",
      "itas",
    ],
    maxConsRun: 2,
    maxVowelRun: 3,
    minVowelRatio: 0.35,
    treatYAsVowel: true,
    minSyllables: 2,
    maxSyllables: 5,
    clusterLinker: "e",
    vowelLinker: "l",
  },
  CELESTIC: {
    onsets: [
      "a",
      "ae",
      "e",
      "el",
      "al",
      "il",
      "ol",
      "ul",
      "cel",
      "ser",
      "ver",
      "lir",
      "aur",
      "eir",
      "mir",
      "thal",
      "val",
    ],
    vowels: [
      "a",
      "e",
      "i",
      "o",
      "u",
      "ae",
      "ea",
      "ai",
      "ia",
      "ie",
      "io",
      "ou",
      "ui",
    ],
    codas: ["l", "n", "r", "s", "th", "el", "iel", "ar", "is", "as"],
    codaChance: 0.55,
    medials: ["ael", "iel", "ion", "ora", "iel", "ir", "ara", "uri", "arion"],
    medialMorphChance: 0.6,
    suffixes: ["iel", "ael", "ion", "ora", "is", "arion", "iel", "eth"],
    maxConsRun: 2,
    maxVowelRun: 2,
    minVowelRatio: 0.4,
    treatYAsVowel: true,
    minSyllables: 2,
    maxSyllables: 5,
    clusterLinker: "e",
    vowelLinker: "r",
  },
  INFERNIC: {
    onsets: [
      "gr",
      "kr",
      "dr",
      "br",
      "thr",
      "vr",
      "zr",
      "kl",
      "sk",
      "sn",
      "gn",
      "vrog",
      "ulg",
      "zor",
      "rak",
      "gash",
      "morg",
    ],
    vowels: ["a", "o", "u", "e", "ia", "oa", "ua", "ai", "oi"],
    codas: ["th", "k", "g", "r", "z", "x", "sh", "kh", "gh", "n", "m"],
    codaChance: 0.75,
    medials: [
      "gor",
      "zul",
      "rak",
      "thr",
      "khar",
      "vur",
      "drak",
      "mor",
      "gron",
      "vul",
    ],
    medialMorphChance: 0.45,
    suffixes: ["oth", "ar", "rak", "gul", "zor", "eth", "uzad", "ash", "ath"],
    maxConsRun: 4,
    maxVowelRun: 4,
    minVowelRatio: 0.2,
    treatYAsVowel: false,
    minSyllables: 2,
    maxSyllables: 5,
    clusterLinker: "a",
    vowelLinker: "r",
  },
  ARCANE: {
    onsets: [
      "a",
      "e",
      "i",
      "o",
      "u",
      "x",
      "z",
      "v",
      "q",
      "k",
      "s",
      "r",
      "th",
      "sh",
      "ch",
      "ph",
      "gh",
      "xa",
      "xi",
      "ze",
      "zy",
      "qu",
      "ka",
      "ly",
      "sy",
      "va",
      "or",
      "ny",
    ],
    vowels: ["a", "e", "i", "o", "u", "ae", "ia", "ie", "io", "ei", "ou", "ui"],
    codas: ["n", "r", "s", "th", "x", "z", "sh", "m", "l", "t"],
    codaChance: 0.6,
    medials: [
      "ar",
      "en",
      "is",
      "os",
      "ith",
      "al",
      "or",
      "ir",
      "um",
      "ex",
      "ul",
    ],
    medialMorphChance: 0.5,
    suffixes: ["ar", "en", "is", "os", "ith", "or", "ul", "um", "ae", "ion"],
    maxConsRun: 3,
    maxVowelRun: 3,
    minVowelRatio: 0.3,
    treatYAsVowel: true,
    minSyllables: 2,
    maxSyllables: 5,
    clusterLinker: "e",
    vowelLinker: "r",
  },
  DEEP_SPEECH: {
    onsets: [
      "gh",
      "gr",
      "kr",
      "zr",
      "zh",
      "xh",
      "kl",
      "ql",
      "k’",
      "x’",
      "t’",
      "sh",
      "sk",
      "thl",
      "vr",
      "vx",
      "dl",
      "rk",
    ],
    vowels: ["a", "u", "o", "e", "ia", "ua", "ao", "ou", ""],
    codas: ["th", "x", "g", "k", "z", "sh", "’th", "’x", "’g", "n"],
    codaChance: 0.8,
    medials: [
      "ul",
      "gur",
      "zha",
      "kth",
      "rax",
      "xul",
      "gath",
      "urh",
      "shul",
      "vrax",
      "qor",
      "thrul",
      "zoth",
    ],
    medialMorphChance: 0.45,
    suffixes: [
      "’thul",
      "’gath",
      "’nax",
      "’ul",
      "’rax",
      "oth",
      "zoth",
      "gath",
      "khul",
    ],
    maxConsRun: 4,
    maxVowelRun: 4,
    minVowelRatio: 0.2,
    treatYAsVowel: false,
    minSyllables: 2,
    maxSyllables: 5,
    clusterLinker: "’",
    vowelLinker: "h",
  },
  GOBLINIC: {
    onsets: [
      "g",
      "gr",
      "kr",
      "kl",
      "sn",
      "sk",
      "sm",
      "sp",
      "st",
      "tr",
      "dr",
      "bl",
      "br",
      "pl",
      "gl",
      "zz",
      "gn",
      "ch",
      "sc",
    ],
    vowels: ["a", "e", "i", "o", "u", "aa", "oo", "ei", "oi"],
    codas: ["k", "g", "n", "m", "b", "t", "z", "zz", "sh", "p", "x", ""],
    codaChance: 0.7,
    medials: [
      "grub",
      "snag",
      "krat",
      "blit",
      "skrag",
      "drub",
      "gnar",
      "plok",
      "zib",
      "krin",
      "grot",
      "snib",
    ],
    medialMorphChance: 0.45,
    suffixes: [
      "ak",
      "ig",
      "ok",
      "nob",
      "zit",
      "gob",
      "bag",
      "pik",
      "nip",
      "ogg",
    ],
    maxConsRun: 3,
    maxVowelRun: 3,
    minVowelRatio: 0.28,
    treatYAsVowel: false,
    minSyllables: 2,
    maxSyllables: 5,
    clusterLinker: "i",
    vowelLinker: "g",
  },
  TECHNARCH: {
    onsets: [
      "auto",
      "mecha",
      "syn",
      "alg",
      "dat",
      "net",
      "cyb",
      "neuro",
      "quant",
      "proto",
      "nano",
      "vector",
      "core",
      "node",
      "grid",
      "flux",
      "servo",
    ],
    vowels: ["a", "e", "i", "o", "u", "ai", "io", "ea", "ou", "ui"],
    codas: ["on", "ix", "ex", "um", "is", "os", "", "core"],
    codaChance: 0.6,
    medials: [
      "tron",
      "link",
      "proc",
      "calc",
      "mach",
      "net",
      "bot",
      "loop",
      "core",
      "data",
    ],
    medialMorphChance: 0.5,
    suffixes: ["on", "ix", "ex", "ium", "aris", "logicus", "tek", "sys"],
    maxConsRun: 3,
    maxVowelRun: 3,
    minVowelRatio: 0.3,
    treatYAsVowel: true,
    minSyllables: 2,
    maxSyllables: 6,
    clusterLinker: "e",
    vowelLinker: "l",
  },
  SIRENIC: {
    onsets: [
      "a",
      "e",
      "i",
      "o",
      "u",
      "l",
      "n",
      "m",
      "s",
      "v",
      "r",
      "h",
      "w",
      "sh",
      "th",
      "ph",
      "ch",
      "wh",
      "ly",
      "ny",
      "sel",
      "sir",
      "mar",
      "nai",
      "ora",
      "thal",
      "vel",
      "mel",
      "lun",
      "aqu",
      "ond",
    ],
    vowels: [
      "a",
      "e",
      "i",
      "o",
      "u",
      "ae",
      "ai",
      "ea",
      "ee",
      "ia",
      "ie",
      "io",
      "oa",
      "oe",
      "ou",
      "ua",
      "ue",
      "ui",
    ],
    codas: [
      "n",
      "r",
      "l",
      "s",
      "th",
      "sh",
      "h",
      "m",
      "el",
      "en",
      "ir",
      "is",
      "a",
      "ia",
      "ine",
    ],
    codaChance: 0.45,
    medials: [
      "ara",
      "ela",
      "ine",
      "ora",
      "ula",
      "iri",
      "oni",
      "ari",
      "una",
      "esi",
      "mar",
      "sel",
      "vai",
      "wen",
      "lua",
      "nys",
    ],
    medialMorphChance: 0.4,
    suffixes: [
      "ine",
      "is",
      "ir",
      "iel",
      "ora",
      "ara",
      "una",
      "elle",
      "en",
      "ys",
      "eth",
      "wen",
    ],
    maxConsRun: 2,
    maxVowelRun: 4,
    minVowelRatio: 0.4,
    treatYAsVowel: true,
    minSyllables: 2,
    maxSyllables: 6,
    clusterLinker: "l",
    vowelLinker: "n",
  },
  OOGA_BOOGA: {
    onsets: [
      "",
      "b",
      "g",
      "k",
      "m",
      "n",
      "t",
      "p",
      "w",
      "h",
      "bg",
      "gb",
      "gr",
      "kr",
    ],
    vowels: ["o", "a", "u", "oo", "oa", "ou", "ua", "uga", "oga"],
    codas: ["", "g", "k", "ng", "ga", "ka", "gk"],
    codaChance: 0.72,
    medials: [
      "ooga",
      "booga",
      "boga",
      "maka",
      "taka",
      "gora",
      "gugu",
      "koko",
      "boko",
    ],
    medialMorphChance: 0.35,
    suffixes: ["uga", "booga", "g", "ka", "ko", "ga", "bog", "ok"],
    maxConsRun: 2,
    maxVowelRun: 4,
    minVowelRatio: 0.4,
    treatYAsVowel: false,
    minSyllables: 2,
    maxSyllables: 5,
    clusterLinker: "g",
    vowelLinker: "k",
  },
  DWARVISH: {
    onsets: [
      "b",
      "d",
      "g",
      "k",
      "m",
      "n",
      "r",
      "t",
      "v",
      "z",
      "br",
      "dr",
      "gr",
      "kr",
      "tr",
      "thr",
      "kh",
    ],
    vowels: ["a", "e", "i", "o", "u", "ai", "oi", "au"],
    codas: [
      "r",
      "n",
      "m",
      "k",
      "g",
      "d",
      "nd",
      "rd",
      "ld",
      "rn",
      "rm",
      "rg",
      "rk",
    ],
    codaChance: 0.75,
    medials: [
      "dur",
      "grim",
      "bar",
      "kar",
      "grom",
      "thal",
      "dun",
      "fund",
      "brak",
      "stenn",
      "stein",
    ],
    medialMorphChance: 0.45,
    suffixes: ["in", "ar", "orn", "grin", "dun", "hald", "heim", "hold"],
    maxConsRun: 3,
    maxVowelRun: 3,
    minVowelRatio: 0.28,
    treatYAsVowel: false,
    minSyllables: 2,
    maxSyllables: 5,
    clusterLinker: "e",
    vowelLinker: "r",
  },
  HALFLING: {
    onsets: [
      "b",
      "d",
      "f",
      "g",
      "h",
      "j",
      "k",
      "l",
      "m",
      "n",
      "p",
      "r",
      "s",
      "t",
      "w",
      "br",
      "cl",
      "fl",
      "pl",
      "wh",
    ],
    vowels: ["a", "e", "i", "o", "u", "ie", "ea", "ai", "oa", "oi", "oo"],
    codas: ["n", "r", "l", "m", "s", "t", "ck", "nd", "rt", "ft", "ley", "ton"],
    codaChance: 0.55,
    medials: [
      "apple",
      "bur",
      "brook",
      "dale",
      "mill",
      "merry",
      "will",
      "hedge",
      "bottle",
      "puddle",
    ],
    medialMorphChance: 0.3,
    suffixes: [
      "ton",
      "ford",
      "wick",
      "brook",
      "hill",
      "bury",
      "shaw",
      "combe",
      "ley",
    ],
    maxConsRun: 2,
    maxVowelRun: 3,
    minVowelRatio: 0.35,
    treatYAsVowel: true,
    minSyllables: 2,
    maxSyllables: 5,
    clusterLinker: "e",
    vowelLinker: "l",
  },
  NOCTURNIC: {
    onsets: [
      "v",
      "s",
      "z",
      "r",
      "l",
      "m",
      "n",
      "d",
      "t",
      "c",
      "ch",
      "sh",
      "vr",
      "cr",
      "dr",
      "str",
    ],
    vowels: ["a", "e", "i", "o", "u", "ae", "ei", "ia", "io", "ou", "ui"],
    codas: ["r", "s", "th", "x", "z", "n", "l", "re", "is", "us", "oth", "yx"],
    codaChance: 0.65,
    medials: [
      "nos",
      "sang",
      "vel",
      "mor",
      "car",
      "lac",
      "umbr",
      "noir",
      "vlad",
      "rav",
      "dusk",
    ],
    medialMorphChance: 0.45,
    suffixes: ["ius", "elle", "oire", "an", "ar", "or", "yx", "ath", "osa"],
    maxConsRun: 3,
    maxVowelRun: 3,
    minVowelRatio: 0.3,
    treatYAsVowel: true,
    minSyllables: 2,
    maxSyllables: 6,
    clusterLinker: "e",
    vowelLinker: "r",
  },
  DERPTONGUE: {
    onsets: [
      "b",
      "g",
      "k",
      "p",
      "d",
      "t",
      "f",
      "m",
      "n",
      "r",
      "s",
      "bl",
      "gr",
      "kr",
      "sn",
      "pl",
      "fl",
      "z",
      "v",
    ],
    vowels: ["a", "e", "i", "o", "u", "oo", "ee", "uh", "ah", "ow"],
    codas: ["", "g", "k", "p", "t", "n", "m", "b", "sh", "zz", "rp", "nk"],
    codaChance: 0.6,
    medials: [
      "derp",
      "blor",
      "snar",
      "plop",
      "gorp",
      "flub",
      "drool",
      "bonk",
      "boop",
    ],
    medialMorphChance: 0.55,
    suffixes: ["er", "us", "o", "ee", "oo", "ah", "uh", "boop", "onk"],
    maxConsRun: 2,
    maxVowelRun: 4,
    minVowelRatio: 0.33,
    treatYAsVowel: true,
    minSyllables: 2,
    maxSyllables: 6,
    clusterLinker: "e",
    vowelLinker: "p",
  },
  TOADISH: {
    onsets: [
      "gr",
      "kr",
      "br",
      "cro",
      "fro",
      "gl",
      "pl",
      "r",
      "bl",
      "cr",
      "tr",
      "dr",
    ],
    vowels: ["o", "u", "oo", "oa", "ou", "uh", "a", "ua"],
    codas: ["g", "k", "rk", "rg", "mp", "b", "bb", "gk", "nk", "rr", "p"],
    codaChance: 0.75,
    medials: ["croa", "rib", "grub", "glo", "slop", "murk", "drib", "blob"],
    medialMorphChance: 0.45,
    suffixes: ["og", "ug", "ump", "ok", "ogg", "onk", "croak"],
    maxConsRun: 3,
    maxVowelRun: 3,
    minVowelRatio: 0.28,
    treatYAsVowel: false,
    minSyllables: 2,
    maxSyllables: 5,
    clusterLinker: "r",
    vowelLinker: "g",
  },
  BANANAIC: {
    onsets: [
      "",
      "b",
      "d",
      "g",
      "k",
      "m",
      "n",
      "p",
      "t",
      "w",
      "h",
      "ba",
      "na",
      "ma",
      "pa",
      "ga",
      "da",
    ],
    vowels: ["a", "e", "i", "o", "u", "aa", "ee", "oo", "ai", "au"],
    codas: ["", "na", "ma", "pa", "ba", "ga", "ka", "la", "ha"],
    codaChance: 0.6,
    medials: [
      "na",
      "nana",
      "mama",
      "papa",
      "gaga",
      "lala",
      "haha",
      "wawa",
      "baba",
      "dada",
    ],
    medialMorphChance: 0.6,
    suffixes: ["na", "nana", "banana", "mana", "pana", "bana", "lala", "haha"],
    maxConsRun: 1,
    maxVowelRun: 4,
    minVowelRatio: 0.5,
    treatYAsVowel: true,
    minSyllables: 2,
    maxSyllables: 6,
    clusterLinker: "",
    vowelLinker: "n",
  },
  LYRICIAN: {
    onsets: [
      "a",
      "e",
      "i",
      "o",
      "u",
      "l",
      "n",
      "m",
      "r",
      "s",
      "v",
      "f",
      "h",
      "y",
      "al",
      "el",
      "il",
      "ol",
      "ul",
      "ar",
      "en",
      "ir",
      "or",
      "ur",
      "ly",
      "ny",
      "th",
      "ph",
    ],
    vowels: ["a", "e", "i", "o", "u", "ai", "ei", "ia", "io", "oa", "ue", "ui"],
    codas: ["l", "n", "r", "s", "th", "m", "el", "en", "ir", "is", "ar", "al"],
    codaChance: 0.45,
    medials: [
      "ara",
      "eli",
      "ian",
      "ora",
      "ina",
      "ira",
      "ala",
      "esi",
      "len",
      "mir",
      "var",
      "ser",
      "vel",
      "lin",
    ],
    medialMorphChance: 0.35,
    suffixes: [
      "iel",
      "is",
      "en",
      "el",
      "ora",
      "ine",
      "ar",
      "eth",
      "iel",
      "ane",
    ],
    maxConsRun: 2,
    maxVowelRun: 4,
    minVowelRatio: 0.4,
    treatYAsVowel: true,
    minSyllables: 2,
    maxSyllables: 6,
    clusterLinker: "e",
    vowelLinker: "l",
  },
  ANGLISH: {
    onsets: [
      "b",
      "br",
      "bl",
      "c",
      "cl",
      "cr",
      "d",
      "dr",
      "f",
      "fl",
      "fr",
      "g",
      "gr",
      "gl",
      "h",
      "j",
      "k",
      "kr",
      "l",
      "m",
      "n",
      "p",
      "pl",
      "pr",
      "r",
      "s",
      "sl",
      "sm",
      "sn",
      "sp",
      "st",
      "sw",
      "t",
      "tr",
      "v",
      "w",
      "wh",
    ],
    vowels: [
      "a",
      "e",
      "i",
      "o",
      "u",
      "ai",
      "ea",
      "ie",
      "oa",
      "oo",
      "ou",
      "uh",
      "ar",
      "er",
    ],
    codas: [
      "b",
      "d",
      "f",
      "g",
      "k",
      "l",
      "m",
      "n",
      "p",
      "r",
      "s",
      "t",
      "ck",
      "nd",
      "nt",
      "st",
      "sp",
      "sh",
      "th",
      "rd",
      "rk",
      "rm",
      "rl",
      "lp",
      "ft",
    ],
    codaChance: 0.6,
    medials: [
      "ing",
      "ish",
      "est",
      "ard",
      "orn",
      "all",
      "and",
      "ell",
      "ock",
      "ump",
      "old",
      "ent",
      "ram",
      "win",
      "ber",
      "ble",
      "trum",
      "croft",
      "shire",
      "worth",
    ],
    medialMorphChance: 0.4,
    suffixes: [
      "ton",
      "ham",
      "worth",
      "wick",
      "well",
      "ford",
      "croft",
      "den",
      "fell",
      "bury",
      "brook",
      "mere",
      "stead",
    ],
    maxConsRun: 3,
    maxVowelRun: 3,
    minVowelRatio: 0.3,
    treatYAsVowel: true,
    minSyllables: 2,
    maxSyllables: 6,
    clusterLinker: "e",
    vowelLinker: "r",
  },
  NEW_ANGLISH: {
    onsets: [
      "a",
      "b",
      "br",
      "c",
      "cl",
      "cr",
      "d",
      "f",
      "fl",
      "fr",
      "g",
      "gl",
      "gr",
      "h",
      "j",
      "k",
      "kr",
      "l",
      "m",
      "n",
      "p",
      "pl",
      "pr",
      "r",
      "s",
      "sl",
      "sm",
      "sp",
      "st",
      "t",
      "tr",
      "v",
      "w",
      "well",
      "brook",
      "grove",
      "nex",
      "ever",
      "fair",
      "north",
      "east",
      "west",
      "green",
      "bright",
      "clear",
      "sil",
      "blue",
      "gold",
    ],
    vowels: [
      "a",
      "e",
      "i",
      "o",
      "u",
      "ai",
      "ea",
      "ie",
      "oa",
      "ou",
      "ar",
      "er",
      "or",
    ],
    codas: [
      "n",
      "r",
      "s",
      "t",
      "m",
      "l",
      "d",
      "k",
      "x",
      "nd",
      "nt",
      "rd",
      "rn",
      "st",
      "ft",
      "den",
      "ton",
      "ford",
      "ly",
    ],
    codaChance: 0.5,
    medials: [
      "well",
      "brook",
      "vale",
      "fold",
      "ridge",
      "moor",
      "bank",
      "port",
      "field",
      "mill",
      "crest",
      "grove",
      "point",
      "gate",
      "worth",
      "ford",
      "haven",
      "side",
      "wick",
      "holt",
      "mark",
    ],
    medialMorphChance: 0.4,
    suffixes: [
      "well",
      "fold",
      "worth",
      "ridge",
      "vale",
      "hill",
      "gate",
      "point",
      "mill",
      "brook",
      "haven",
      "croft",
      "grove",
      "port",
      "ly",
      "ton",
      "den",
      "sy",
      "corp",
      "soft",
      "tek",
    ],
    maxConsRun: 3,
    maxVowelRun: 3,
    minVowelRatio: 0.3,
    treatYAsVowel: true,
    minSyllables: 2,
    maxSyllables: 6,
    clusterLinker: "e",
    vowelLinker: "r",
  },
  PHRASIC: {
    onsets: [
      "kingdom",
      "princedom",
      "duchy",
      "country",
      "nation",
      "state",
      "municipality",
      "geographic region",
      "empire",
      "republic",
      "caliphate",
      "sultanate",
      "khanate",
    ],
    vowels: [
      " of the ",
      " near the ",
      " beyond the ",
      " under the ",
      " within the ",
      " amidst the ",
      " atop the ",
      " along the ",
      " beside the ",
      " past the ",
      " toward the ",
    ],
    medials: [
      "ancient ",
      "misty ",
      "forgotten ",
      "sleepy ",
      "haunted ",
      "moonlit ",
      "crumbling ",
      "stormy ",
      "shimmering ",
      "quiet ",
      "hidden ",
      "lush ",
      "lonely ",
      "glimmering ",
      "frozen ",
      "sunken ",
      "shattered ",
      "lush ",
      "barren ",
    ],
    medialMorphChance: 0.55,
    codas: [
      "crying moon ",
      "endless soup ",
      "large canyon ",
      "sleepy village ",
      "forgotten beans ",
      "ninth duck ",
      "friendly ghost ",
      "friendly place ",
      "froggy pond ",
      "dank cave ",
      "cheese regrets ",
      "goblin camp ",
      "cat sanctuary ",
      "graves of your ancestors ",
      "questionable wifi ",
      "unseen noodles ",
      "echoing pickle ",
      "eternal goose ",
      "mouse hole ",
      "village of cannibals ",
      "world's largest sandcastle ",
    ],
    codaChance: 1.0,
    suffixes: [
      " retreat",
      " crossing",
      " hollow",
      " falls",
      " creek",
      " point",
      " pass",
      " trail",
      " rest",
      " bend",
      " grove",
    ],
    maxConsRun: 6,
    maxVowelRun: 8,
    minVowelRatio: 0.1,
    treatYAsVowel: true,
    minSyllables: 1,
    maxSyllables: 1,
    clusterLinker: "",
    vowelLinker: "",
  },
  AMERICAN_PLACE: {
    onsets: [
      "a",
      "e",
      "i",
      "o",
      "u",
      "y",
      "b",
      "c",
      "d",
      "f",
      "g",
      "h",
      "k",
      "l",
      "m",
      "n",
      "p",
      "r",
      "s",
      "t",
      "v",
      "w",
      "bl",
      "br",
      "cr",
      "dr",
      "fl",
      "fr",
      "gr",
      "kl",
      "kr",
      "pl",
      "pr",
      "tr",
      "sk",
      "sl",
      "sm",
      "sn",
      "sp",
      "st",
      "sw",
      "sh",
      "ch",
      "wh",
    ],
    vowels: [
      "a",
      "e",
      "i",
      "o",
      "u",
      "ai",
      "ei",
      "oa",
      "ou",
      "ee",
      "oo",
      "ea",
      "ui",
      "au",
    ],
    codas: [
      "n",
      "m",
      "l",
      "r",
      "s",
      "t",
      "nd",
      "nt",
      "st",
      "rd",
      "rt",
      "rk",
      "rn",
      "rm",
      "sh",
      "ch",
    ],
    codaChance: 0.6,
    medials: [
      "cedar",
      "pine",
      "fir",
      "spruce",
      "moss",
      "fern",
      "stone",
      "river",
      "sound",
      "bay",
      "cove",
      "harbor",
      "mount",
      "peak",
      "rain",
      "fog",
      "coast",
      "trail",
      "falls",
      "glen",
      "grove",
      "ridge",
      "forest",
      "isle",
      "port",
    ],
    medialMorphChance: 0.55,
    suffixes: [
      "ton",
      "ville",
      "port",
      "haven",
      "bay",
      "harbor",
      "falls",
      "grove",
      "ridge",
      "view",
      "dale",
      "river",
      "sound",
      "coast",
      "point",
      "beach",
      "isle",
      "field",
      "mount",
      "springs",
      "trail",
      "landing",
    ],
    maxConsRun: 3,
    maxVowelRun: 2,
    minVowelRatio: 0.35,
    treatYAsVowel: true,
    minSyllables: 2,
    maxSyllables: 4,
    clusterLinker: "a",
    vowelLinker: "r",
  },
  ONOMATOPOEIC: {
    onsets: [
      "b",
      "p",
      "t",
      "d",
      "k",
      "g",
      "ch",
      "sh",
      "s",
      "z",
      "f",
      "v",
      "wh",
      "m",
      "n",
      "r",
      "l",
      "cl",
      "cr",
      "dr",
      "fl",
      "fr",
      "gl",
      "gr",
      "pl",
      "pr",
      "sl",
      "sn",
      "sp",
      "st",
      "sw",
      "th",
      "bl",
      "br",
      "tr",
      "wr",
    ],
    vowels: [
      "a",
      "e",
      "i",
      "o",
      "u",
      "oo",
      "ee",
      "ah",
      "uh",
      "ow",
      "oi",
      "ay",
      "aw",
      "er",
      "ya",
    ],
    codas: [""],
    codaChance: 0.8,
    medials: [
      "bang",
      "buzz",
      "crash",
      "clang",
      "ding",
      "bop",
      "wham",
      "splash",
      "crunch",
      "snap",
      "thud",
      "whirr",
      "fizz",
      "whoosh",
      "click",
      "clack",
      "clonk",
      "drip",
      "drop",
      "plop",
      "pop",
      "smack",
      "zing",
      "zoom",
    ],
    medialMorphChance: 0.6,
    suffixes: [
      "o",
      "a",
      "ah",
      "ee",
      "oo",
      "um",
      "zap",
      "bang",
      "pop",
      "boing",
      "wham",
      "crash",
      "chop",
      "buzz",
      "thunk",
      "swoosh",
      "zap",
      "kaboom",
      "whizz",
    ],
    maxConsRun: 3,
    maxVowelRun: 3,
    minVowelRatio: 0.45,
    treatYAsVowel: true,
    minSyllables: 2,
    maxSyllables: 3,
    clusterLinker: "",
    vowelLinker: "",
  },
  CRETAN: {
    onsets: [
      "a",
      "e",
      "i",
      "o",
      "u",
      "k",
      "p",
      "t",
      "n",
      "m",
      "l",
      "r",
      "s",
      "d",
      "b",
      "g",
      "x",
      "ch",
      "ph",
      "th",
      "kr",
      "kl",
      "kn",
      "pr",
      "tr",
      "dr",
      "br",
      "st",
      "sk",
      "sm",
      "sp",
      "vr",
      "fr",
      "gr",
      "ps",
    ],
    vowels: [
      "a",
      "e",
      "i",
      "o",
      "u",
      "ai",
      "ei",
      "oi",
      "ou",
      "au",
      "ia",
      "io",
      "ea",
      "eo",
    ],
    codas: [
      "s",
      "n",
      "r",
      "m",
      "l",
      "os",
      "on",
      "as",
      "is",
      "es",
      "thos",
      "ros",
      "tos",
      "nos",
    ],
    codaChance: 0.65,
    medials: [
      "mino",
      "knos",
      "thera",
      "kyra",
      "akro",
      "amni",
      "arkad",
      "phaes",
      "kydon",
      "melid",
      "ion",
      "lass",
      "herm",
      "gaia",
      "kalos",
      "neka",
      "doro",
      "kris",
      "anem",
      "pyrg",
      "lyth",
      "zyra",
    ],
    medialMorphChance: 0.55,
    suffixes: [
      "os",
      "los",
      "on",
      "ia",
      "is",
      "as",
      "es",
      "inos",
      "idas",
      "ion",
      "ara",
      "thos",
      "ros",
      "dos",
      "nos",
      "yra",
    ],
    maxConsRun: 2,
    maxVowelRun: 2,
    minVowelRatio: 0.4,
    treatYAsVowel: false,
    minSyllables: 2,
    maxSyllables: 5,
    clusterLinker: "a",
    vowelLinker: "n",
  },
  GAULISH: {
    onsets: [
      "a",
      "e",
      "i",
      "o",
      "u",
      "y",
      "b",
      "c",
      "d",
      "g",
      "l",
      "m",
      "n",
      "p",
      "r",
      "s",
      "t",
      "v",
      "br",
      "cr",
      "dr",
      "gr",
      "pr",
      "tr",
      "bl",
      "cl",
      "gl",
      "pl",
      "gn",
      "sn",
      "st",
      "sk",
      "gw",
      "dw",
      "sw",
    ],
    vowels: [
      "a",
      "e",
      "i",
      "o",
      "u",
      "ai",
      "ei",
      "oi",
      "ou",
      "au",
      "ia",
      "io",
      "uo",
      "eu",
    ],
    codas: [
      "n",
      "r",
      "s",
      "l",
      "m",
      "x",
      "nos",
      "rix",
      "mar",
      "dor",
      "dur",
      "tan",
      "ron",
      "lon",
      "tor",
      "con",
      "dos",
    ],
    codaChance: 0.7,
    medials: [
      "carn",
      "brig",
      "duno",
      "mag",
      "nem",
      "ver",
      "seg",
      "treb",
      "arv",
      "corb",
      "belg",
      "vind",
      "cam",
      "and",
      "lux",
      "dubr",
      "tan",
      "tor",
      "brog",
      "pen",
      "rhed",
      "rix",
      "allon",
      "catu",
      "mor",
      "nemet",
    ],
    medialMorphChance: 0.6,
    suffixes: [
      "dunum",
      "magus",
      "briga",
      "ritum",
      "conna",
      "rix",
      "on",
      "ix",
      "acos",
      "atis",
      "marus",
      "torum",
      "tanum",
      "durum",
      "briva",
      "sarton",
      "lonna",
      "ancon",
      "morion",
    ],
    maxConsRun: 3,
    maxVowelRun: 2,
    minVowelRatio: 0.35,
    treatYAsVowel: true,
    minSyllables: 2,
    maxSyllables: 5,
    clusterLinker: "a",
    vowelLinker: "n",
  },
  NORSE: {
    onsets: [
      "a",
      "e",
      "i",
      "o",
      "u",
      "y",
      "b",
      "d",
      "f",
      "g",
      "h",
      "k",
      "l",
      "m",
      "n",
      "r",
      "s",
      "t",
      "v",
      "bl",
      "br",
      "dr",
      "gr",
      "kr",
      "pr",
      "tr",
      "sk",
      "sn",
      "st",
      "sv",
      "sm",
      "hl",
      "hr",
      "hn",
      "fj",
      "gj",
      "kj",
      "thr",
      "th",
      "kn",
    ],
    vowels: ["a", "e", "i", "o", "u", "y", "ae", "ei", "au", "oy"],
    codas: [
      "r",
      "n",
      "l",
      "s",
      "m",
      "t",
      "k",
      "rn",
      "nd",
      "ld",
      "rd",
      "rk",
      "sk",
      "st",
      "tt",
      "f",
      "g",
      "ng",
      "nn",
      "ss",
    ],
    codaChance: 0.7,
    medials: [
      "fjall",
      "heim",
      "fjord",
      "vik",
      "dal",
      "gard",
      "stad",
      "borg",
      "sund",
      "ness",
      "fjordr",
      "holt",
      "lund",
      "finn",
      "skog",
      "bryn",
      "ulf",
      "stein",
      "eld",
      "vatn",
      "havn",
      "sand",
      "fjord",
      "bak",
      "kross",
      "drang",
    ],
    medialMorphChance: 0.6,
    suffixes: [
      "heim",
      "fjord",
      "vik",
      "dal",
      "gard",
      "stad",
      "borg",
      "ness",
      "holt",
      "lund",
      "fjordr",
      "fjordir",
      "fell",
      "vatn",
      "havn",
      "fjordur",
      "fjordin",
      "fjordrheim",
      "fjordvik",
      "heimr",
    ],
    maxConsRun: 3,
    maxVowelRun: 2,
    minVowelRatio: 0.3,
    treatYAsVowel: true,
    minSyllables: 1,
    maxSyllables: 3,
    clusterLinker: "a",
    vowelLinker: "r",
  },
  THAI: {
    onsets: [
      "a",
      "e",
      "i",
      "o",
      "u",
      "b",
      "ch",
      "d",
      "f",
      "h",
      "k",
      "kh",
      "l",
      "m",
      "n",
      "ng",
      "p",
      "ph",
      "r",
      "s",
      "t",
      "th",
      "w",
      "y",
      "kl",
      "kr",
      "phl",
      "phr",
      "pr",
      "tr",
      "thl",
      "ch",
      "khw",
      "kw",
      "ng",
    ],
    vowels: [
      "a",
      "e",
      "i",
      "o",
      "u",
      "aa",
      "ee",
      "ii",
      "oo",
      "uu",
      "ai",
      "ao",
      "ia",
      "ua",
      "uea",
      "oe",
      "ui",
    ],
    codas: ["n", "ng", "m", "k", "t", "p", "an", "am", "ang", "at", "ap", "ak"],
    codaChance: 0.55,
    medials: [
      "ban",
      "chiang",
      "thong",
      "sai",
      "klong",
      "lam",
      "na",
      "nong",
      "phra",
      "chai",
      "thai",
      "sam",
      "rat",
      "tha",
      "yan",
      "rang",
      "pa",
      "muang",
      "wiang",
      "dong",
      "lom",
      "lak",
      "phon",
      "pha",
      "wan",
    ],
    medialMorphChance: 0.55,
    suffixes: [
      "buri",
      "ratcha",
      "thani",
      "phum",
      "nai",
      "nakhon",
      "lam",
      "chai",
      "sak",
      "yai",
      "noi",
      "wan",
      "daeng",
      "lek",
      "phat",
      "nong",
      "pathum",
      "thong",
      "phra",
      "sam",
      "sawan",
      "muang",
    ],
    maxConsRun: 2,
    maxVowelRun: 3,
    minVowelRatio: 0.45,
    treatYAsVowel: true,
    minSyllables: 2,
    maxSyllables: 3,
    clusterLinker: "a",
    vowelLinker: "n",
  },
  SWAHILI: {
    onsets: [
      "a",
      "e",
      "i",
      "o",
      "u",
      "b",
      "ch",
      "d",
      "f",
      "g",
      "h",
      "j",
      "k",
      "l",
      "m",
      "n",
      "p",
      "r",
      "s",
      "t",
      "v",
      "w",
      "y",
      "z",
      "bw",
      "kw",
      "mw",
      "sw",
      "ny",
      "ng",
      "nd",
      "mb",
      "mj",
      "nj",
    ],
    vowels: [
      "a",
      "e",
      "i",
      "o",
      "u",
      "aa",
      "ee",
      "oo",
      "ua",
      "ia",
      "ai",
      "au",
      "ei",
    ],
    codas: [
      "a",
      "e",
      "i",
      "o",
      "u",
      "la",
      "na",
      "ma",
      "ra",
      "ba",
      "ka",
      "sa",
      "ta",
      "za",
      "ga",
    ],
    codaChance: 0.4,
    medials: [
      "kili",
      "zani",
      "mara",
      "safa",
      "pemba",
      "ziba",
      "tanga",
      "moyo",
      "bahari",
      "nyota",
      "mwanga",
      "simba",
      "rafi",
      "mani",
      "kulu",
      "mali",
      "bora",
      "uzuri",
      "jua",
      "kaya",
      "pwani",
      "tembo",
      "uhuru",
      "rafiki",
      "anga",
      "ziwa",
      "muya",
      "fala",
    ],
    medialMorphChance: 0.55,
    suffixes: [
      "bora",
      "safi",
      "tanga",
      "zani",
      "puri",
      "moyo",
      "bahari",
      "mara",
      "pwani",
      "nuru",
      "zuri",
      "rafiki",
      "mali",
      "tembo",
      "nyota",
      "wazi",
      "ngoma",
      "kaya",
    ],
    maxConsRun: 2,
    maxVowelRun: 3,
    minVowelRatio: 0.5,
    treatYAsVowel: true,
    minSyllables: 2,
    maxSyllables: 4,
    clusterLinker: "a",
    vowelLinker: "n",
  },
  ARABIC: {
    onsets: [
      "a",
      "e",
      "i",
      "o",
      "u",
      "b",
      "d",
      "f",
      "g",
      "h",
      "j",
      "k",
      "l",
      "m",
      "n",
      "q",
      "r",
      "s",
      "t",
      "w",
      "y",
      "z",
      "sh",
      "kh",
      "gh",
      "th",
      "dh",
      "sa",
      "za",
      "fa",
      "ha",
      "ta",
      "na",
      "ra",
    ],
    vowels: ["a", "i", "u", "ai", "au", "ia", "ua", "ei", "ou"],
    codas: [
      "n",
      "m",
      "r",
      "s",
      "l",
      "d",
      "h",
      "t",
      "b",
      "f",
      "an",
      "ah",
      "ar",
      "at",
      "as",
      "un",
      "am",
      "im",
      "id",
      "ir",
      "ul",
      "ur",
    ],
    codaChance: 0.7,
    medials: [
      "rah",
      "sala",
      "nura",
      "malik",
      "amir",
      "jabal",
      "wadi",
      "qamar",
      "sharq",
      "gharb",
      "layl",
      "nur",
      "najm",
      "safa",
      "zahir",
      "barq",
      "aziz",
      "jamal",
      "iman",
      "hakim",
      "fajr",
      "sabir",
      "rasul",
      "tariq",
      "zaman",
      "khidr",
      "samir",
      "raha",
      "siraj",
      "karim",
    ],
    medialMorphChance: 0.6,
    suffixes: [
      "ah",
      "an",
      "ar",
      "at",
      "un",
      "iya",
      "iyyah",
      "een",
      "oon",
      "abad",
      "stan",
      "iyya",
      "iyah",
      "lah",
      "rah",
      "din",
      "mal",
      "bar",
      "ram",
      "mun",
    ],
    maxConsRun: 2,
    maxVowelRun: 2,
    minVowelRatio: 0.35,
    treatYAsVowel: true,
    minSyllables: 2,
    maxSyllables: 5,
    clusterLinker: "a",
    vowelLinker: "l",
  },
  HEBREW: {
    onsets: [
      "a",
      "e",
      "i",
      "o",
      "u",
      "b",
      "d",
      "g",
      "h",
      "k",
      "l",
      "m",
      "n",
      "p",
      "r",
      "s",
      "t",
      "sh",
      "ch",
      "tz",
      "z",
      "y",
      "v",
      "br",
      "dr",
      "kr",
      "pr",
      "sr",
      "tr",
      "bn",
      "ml",
      "shl",
      "chl",
      "tz",
      "yh",
    ],
    vowels: [
      "a",
      "e",
      "i",
      "o",
      "u",
      "ai",
      "ei",
      "oi",
      "au",
      "ia",
      "ua",
      "aa",
      "ee",
      "oo",
    ],
    codas: [
      "n",
      "m",
      "l",
      "r",
      "s",
      "t",
      "h",
      "el",
      "am",
      "on",
      "en",
      "ah",
      "im",
      "oth",
      "an",
      "ar",
      "et",
    ],
    codaChance: 0.8,
    medials: [
      "beth",
      "el",
      "shal",
      "yah",
      "zur",
      "ram",
      "har",
      "dav",
      "shalom",
      "bar",
      "oren",
      "amir",
      "nahal",
      "tzur",
      "lev",
      "raam",
      "eden",
      "dor",
      "aviv",
      "yeru",
      "hadar",
      "tamar",
      "noam",
      "gil",
      "shom",
      "sion",
      "eshel",
    ],
    medialMorphChance: 0.5,
    suffixes: [
      "el",
      "ah",
      "on",
      "eth",
      "im",
      "oth",
      "an",
      "ar",
      "or",
      "am",
      "yah",
      "iel",
      "zion",
      "ram",
      "dor",
      "lev",
      "tam",
      "esh",
      "oth",
      "ur",
    ],
    maxConsRun: 2,
    maxVowelRun: 2,
    minVowelRatio: 0.35,
    treatYAsVowel: true,
    minSyllables: 2,
    maxSyllables: 4,
    clusterLinker: "a",
    vowelLinker: "h",
  },
};
