export const Languages = [
    "QUECHUA",
    // "NAHUATL",
    // "SANSKRITIC",
    // "BABYLONIAN",
    // "ETRUSCAN",
    // "GAULISH",
    // "MESOPOTAMIC",
    // "EGYPTIC",
    // "ROMANCE",
    // "GERMANIC",
    // "TURKIC",
    // "SEMITIC",
    // "BANTU_LIKE",
    // "AFRICAN_WEST",
    // "AFRICAN_HORN",
    // "CN",
    // "JP",
    // "POLYNESIAN",
    // "MONGOLIC",
    // "GREEKIC",
    // "RUSSIANIC",
    // "LATINIC",
    // "CELESTIC",
    // "INFERNIC",
    // "ARCANE",
    // "DEEP_SPEECH",
    // "GOBLINIC",
    // "TECHNARCH",
    // "FUEGIC",
    // "SIRENIC",
    // "OOGA_BOOGA",
    // "DWARVISH",
    // "HALFLING",
    // "NOCTURNIC",
    // "DERPTONGUE",
    // "TOADISH",
    // "BANANAIC",
    // "LYRICIAN",
    // "ANGLISHIC",
    // "NEW_ANGLISHIC",
    // "PHRASIC",
] as const;

export type Language = (typeof Languages)[number];

type LanguageConfig = {
    onsets: string[];
    vowels: string[];
    codas: string[];
    codaChance: number;
    medials: string[];
    medialMorphChance: number;
    suffixes: string[],
    maxConsRun: number,
    maxVowelRun: number,
    minVowelRatio: number,
    treatYAsVowel: boolean,
    minSyllables: number,
    maxSyllables: number,
    clusterLinker: string,
    vowelLinker: string,
};

// A few reusable vowel bundles to bias families
const V_OPEN = [
    "a",
    "e",
    "i",
    "o",
    "u"
];
const V_DIP = [
    "ai",
    "au",
    "ei",
    "ia",
    "io",
    "oa",
    "ue",
    "ui"
];
const V_SOFT = [
    "a",
    "e",
    "i",
    "o",
    "u",
    "ia",
    "io",
    "ie",
    "ea"
];
const V_SEMI = [
    "a",
    "i",
    "u",
    "aa",
    "ii",
    "uu",
    "ai",
    "au"
];

export const languageConfigs: { [k: string]: LanguageConfig } = {
    "QUECHUA": {
        onsets: [
            "a", "i", "u",
            "k", "q", "t", "p", "s", "m", "n", "l", "r", "y", "w", "ch",
            "kh", "qh", "ll", "ny", "hu", "huam", "hua", "han", "hak", "yak", "yac", "sac", "sak"
        ],
        // Quechua core is a–i–u; allow some e/o from Spanish-era flavor sparingly
        vowels: ["a", "i", "u", "ia", "ua", "ai", "iu", "au", "(e)", "(o)"],
        // Mostly open syllables; light codas show up in toponyms
        codas: ["", "n", "k", "q", "s"],
        codaChance: 0.30,
        medials: [
            "pampa", "marka", "suyu", "tambo", "pata", "urcu", "urko", "qucha", "cocha",
            "yaku", "sacha", "chakra", "wasi", "kancha", "suyu", "runa", "ayllu"
        ],
        medialMorphChance: 0.45,
        suffixes: [
            "suyu", "pampa", "marka", "pata", "tambo", "wasi", "qucha", "cocha", "yaku", "sacha", "kancha", "runa"
        ],
        // phonotactics
        maxConsRun: 2,          // Quechuan avoids heavy clusters
        maxVowelRun: 2,         // keeps the CV rhythm tight
        minVowelRatio: 0.40,    // open, singable
        treatYAsVowel: false,   // y ~ glide/consonant
        minSyllables: 2,
        maxSyllables: 5,
        clusterLinker: "i",     // epenthetic i is common
        vowelLinker: "y"        // glide between adjacent vowels
    },
    "NAHUATL": {
        onsets: [
            "a", "e", "i", "o",
            "ka", "ke", "ki", "ko", "kwa", "kwe", "kwi", "kwo",
            "ma", "me", "mi", "mo", "na", "ne", "ni", "no",
            "pa", "pe", "pi", "po", "ta", "te", "ti", "to",
            "tl", "tla", "tle", "tli", "tlo",
            "ya", "ye", "yi", "yo", "hua", "hue", "hui", "huo",
            "cu", "cue", "cui", "co", "qui", "que",
            "za", "ze", "zi", "zo"
        ],
        vowels: ["a", "e", "i", "o", "u", "ia", "ua", "ui", "ei", "oa"],
        codas: ["n", "t", "l", "tl", "lli", "pan", "can", "yan", "hua", "zin", "te", "co"],
        codaChance: 0.65,
        medials: [
            "tlan", "hua", "co", "can", "pan", "te", "xi", "zo", "na", "ya", "otl", "atl", "mix", "tzon", "pilli", "mecatl", "quetz", "chol", "tonal"
        ],
        medialMorphChance: 0.5,
        suffixes: [
            "tlan", "tlal", "co", "can", "pan", "yan", "tepetl", "huacan", "miztli", "quetzal", "tonal", "nahuac", "zuma", "tlani", "teotl"
        ],
        maxConsRun: 2, // Nahuatl avoids huge clusters
        maxVowelRun: 2,
        minVowelRatio: 0.35,
        treatYAsVowel: true,
        minSyllables: 2,
        maxSyllables: 4,
        clusterLinker: "a", // common epenthesis vowel
        vowelLinker: "h"    // soft breath between vowels
    },
    "SANSKRITIC": {
        onsets: [
            "a", "i", "u", "e", "o",
            "ka", "kha", "ga", "gha", "cha", "ch", "ja", "jha", "ta", "tha", "da", "dha",
            "pa", "pha", "ba", "bha", "ma", "na", "ra", "la", "sa", "sha", "sri", "va", "ya", "ha",
            "tra", "dra", "pra", "bra", "kra", "gra", "pla", "gla", "kla", "ksha", "jna"
        ],
        vowels: ["a", "i", "u", "e", "o", "aa", "ii", "uu", "ai", "au", "ri", "ru"],
        codas: ["", "m", "n", "s", "h", "r", "ya", "ra", "na"],
        codaChance: 0.40,
        medials: [
            "indra", "deva", "raja", "pura", "nagara", "giri", "sar", "vara", "varta", "kuta",
            "kaya", "maya", "yoga", "sena", "kashi", "tirtha", "ksetra", "alaya", "bhumi", "ratna"
        ],
        medialMorphChance: 0.50,
        suffixes: [
            "pura", "nagara", "sthana", "desa", "loka", "varsha", "ksetra", "alaya", "ashrama", "mandir", "grama"
        ],
        // phonotactics
        maxConsRun: 3,        // allow clusters like 'ksh', 'str'
        maxVowelRun: 2,
        minVowelRatio: 0.33,
        treatYAsVowel: false, // 'y' behaves as a glide/consonant
        minSyllables: 2,
        maxSyllables: 5,
        clusterLinker: "a",   // Sanskrit loves schwa/‘a’ epenthesis
        vowelLinker: "y"      // glide between vowels (aya/iya/…)
    },
    "BABYLONIAN": {
        onsets: [
            "ab", "ak", "am", "an", "ar", "as", "at", "ba", "bal", "bar", "bel", "bil", "da", "dar", "du",
            "en", "es", "er", "ga", "gal", "gur", "ha", "hal", "ka", "kar", "ku", "la", "lam", "ma", "mar", "mu", "na", "nam",
            "nar", "ni", "nu", "pa", "rab", "ram", "sar", "sha", "sham", "sin", "sum", "tar", "tam", "ur", "ush", "zal", "zim"
        ],
        vowels: ["a", "e", "i", "u", "ia", "ai", "ua", "aa", "ei"],
        codas: ["n", "m", "r", "l", "sh", "t", "k", "s", "b", "g", "z", "th", "um", "il"],
        codaChance: 0.7,
        medials: [
            "ash", "esh", "ish", "ush", "nin", "bel", "mar", "lam", "tam", "ur", "an", "en", "sin",
            "ram", "sam", "bal", "nam", "gal", "dur", "zur", "esh", "mur", "lum", "sum"
        ],
        medialMorphChance: 0.55,
        suffixes: [
            "ra", "ur", "esh", "an", "en", "il", "im", "um", "nin", "lam", "tam", "bel", "duk", "zum", "mar"
        ],
        maxConsRun: 3, maxVowelRun: 2, minVowelRatio: 0.28,
        treatYAsVowel: false, minSyllables: 2, maxSyllables: 5,
        clusterLinker: "u", vowelLinker: "r"
    },
    "ETRUSCAN": {
        onsets: [
            "a", "e", "i", "o", "u",
            "th", "ph", "ch", "cl", "fl", "tr", "vl", "ml", "pl", "vel", "lar", "tur", "uni", "ais", "seth", "arn", "mar"
        ],
        vowels: ["a", "e", "i", "o", "u", "ae", "ai", "ei", "ia", "io", "ui"],
        codas: ["s", "n", "r", "th", "ch", "m", "l", "t", "sna", "ni", "ce"],
        codaChance: 0.55,
        medials: ["lar", "thur", "vel", "uni", "tur", "seth", "arn", "mar", "avl", "clan", "than", "ath", "aci", "nes"],
        medialMorphChance: 0.5,
        suffixes: ["th", "ce", "na", "le", "ra", "chi", "sna", "ni", "thil", "ate"],
        maxConsRun: 2, maxVowelRun: 2, minVowelRatio: 0.35,
        treatYAsVowel: true, minSyllables: 2, maxSyllables: 5,
        clusterLinker: "a", vowelLinker: "l"
    },
    "GAULISH": {
        onsets: [
            "b", "br", "c", "cr", "d", "dr", "g", "gr", "k", "kr", "l", "m", "n", "p", "r", "s", "t", "tr", "v",
            "bel", "bri", "cam", "tre", "gal", "ver", "dun", "mag", "kar", "tar", "pen", "mor"
        ],
        vowels: ["a", "e", "i", "o", "u", "ai", "ei", "oi", "ou", "au"],
        codas: ["n", "s", "r", "l", "m", "t", "c", "x", "th", "d", "os", "ix"],
        codaChance: 0.6,
        medials: ["rix", "mag", "gal", "bri", "treb", "dun", "kar", "tar", "pen", "mor", "vel", "tor", "cam", "mar", "nem"],
        medialMorphChance: 0.45,
        suffixes: ["rix", "on", "os", "ix", "et", "an", "ar", "en", "acos", "atis"],
        maxConsRun: 3, maxVowelRun: 3, minVowelRatio: 0.3,
        treatYAsVowel: true, minSyllables: 2, maxSyllables: 5,
        clusterLinker: "e", vowelLinker: "n"
    },
    "MESOPOTAMIC": {
        onsets: [
            "an", "en", "in", "un", "ur", "ni", "ku", "lu", "mu", "nu", "su",
            "ba", "da", "ga", "ka", "ra", "na", "pa", "ti", "zi",
            "ash", "esh", "ish", "ush", "nin", "ding", "lil", "bel", "mar", "nab", "gil", "is", "tam", "sam"
        ],
        vowels: ["a", "e", "i", "u", "ia", "ai", "ua", "ei", "aa", "uu"],
        codas: ["n", "m", "r", "l", "sh", "t", "k", "s", "b", "g", "z", "th", "ur"],
        codaChance: 0.65,
        medials: [
            "lil", "bel", "ash", "esh", "nin", "ur", "ki", "zu", "ra", "an", "utu", "sin",
            "tam", "nam", "gil", "lam", "esh", "dum", "ish", "mur", "sum", "zur", "mal", "kal"
        ],
        medialMorphChance: 0.55,
        suffixes: [
            "ra", "ur", "esh", "ish", "an", "en", "il", "im", "um", "nin", "lam", "tam", "bel", "duk", "zum", "mar"
        ],
        maxConsRun: 3, maxVowelRun: 2, minVowelRatio: 0.28,
        treatYAsVowel: false, minSyllables: 2, maxSyllables: 5,
        clusterLinker: "u", vowelLinker: "r"
    },
    "EGYPTIC": {
        onsets: [
            "an", "am", "ba", "ka", "ra", "sa", "ma", "na", "pa", "te", "ne",
            "mer", "ket", "sen", "neb", "hotep", "set", "ankh", "khem", "tep", "ram", "mut", "thot", "ptah"
        ],
        vowels: ["a", "e", "i", "o", "u", "aa", "ia", "ai", "au", "ei", "ua", "oa"],
        codas: ["t", "k", "m", "n", "r", "s", "h", "p", "kh", "sh", "pt", "ph", "th", "sek"],
        codaChance: 0.6,
        medials: [
            "ra", "maat", "seth", "amon", "neter", "ankh", "hotep", "nef", "sek", "tep", "amonr", "phar", "mut", "sob", "khaf", "nefer", "ram", "akh", "tem", "sen"
        ],
        medialMorphChance: 0.55,
        suffixes: [
            "hotep", "ankh", "ra", "tep", "mut", "set", "amen", "nef", "sek", "ka", "ur", "het", "shut"
        ],
        maxConsRun: 2, maxVowelRun: 2, minVowelRatio: 0.33,
        treatYAsVowel: false, minSyllables: 2, maxSyllables: 6,
        clusterLinker: "e", vowelLinker: "n"
    },
    "ROMANCE": {
        onsets: [
            "b",
            "c",
            "d",
            "f",
            "g",
            "l",
            "m",
            "n",
            "p",
            "r",
            "s",
            "t",
            "br",
            "cr",
            "dr",
            "fl",
            "gl",
            "gr",
            "pl",
            "pr",
            "tr",
            "vr",
            "ch",
            "cl",
            "fr",
            "bl",
            "ros",
            "san"
        ],
        vowels: [...V_SOFT,
            "ue",
            "eo",
            "ia",
            "io",
            "ai",
            "au"
        ],
        codas: [
            "n",
            "r",
            "s",
            "l",
            "m",
            "t",
            "z"
        ],
        codaChance: 0.5,
        medials: [
            "del",
            "dor",
            "ver",
            "mar",
            "val",
            "lor",
            "ria",
            "lia",
            "mia",
            "fort",
            "bell",
            "ciel",
            "rosa",
            "vino",
            "fior",
            "cast",
            "mont",
            "sant",
            "riv",
            "cor"
        ],
        medialMorphChance: 0.45,
        suffixes: [
            "ia",
            "aria",
            "esia",
            "orio",
            "ano",
            "ino",
            "etta",
            "enza",
            "ella",
            "esco",
            "ura",
            "ito",
            "a",
            "o",
            "es"
        ],
        maxConsRun: 2,
        maxVowelRun: 3,
        minVowelRatio: 0.35,
        treatYAsVowel: true,
        minSyllables: 2,
        maxSyllables: 5,
        clusterLinker: "e",
        vowelLinker: "l"
    },
    "GERMANIC": {
        onsets: [
            "b",
            "d",
            "f",
            "g",
            "h",
            "k",
            "l",
            "m",
            "n",
            "p",
            "r",
            "s",
            "t",
            "w",
            "th",
            "br",
            "cr",
            "dr",
            "fr",
            "gr",
            "kr",
            "pr",
            "tr",
            "st",
            "sk",
            "sp",
            "sn",
            "sm",
            "sw",
            "sch"
        ],
        vowels: [...V_OPEN,
        ...V_DIP,
            "au",
            "ei",
            "ie",
            "oo"
        ],
        codas: [
            "nd",
            "rt",
            "rm",
            "rg",
            "lf",
            "rk",
            "lt",
            "st",
            "sk",
            "n",
            "r",
            "m",
            "l",
            "k",
            "t"
        ],
        codaChance: 0.7,
        medials: [
            "wald",
            "heim",
            "mark",
            "gard",
            "dorf",
            "stein",
            "burg",
            "holt",
            "feld",
            "lund",
            "brun",
            "thal",
            "hart",
            "grim"
        ],
        medialMorphChance: 0.35,
        suffixes: [
            "land",
            "heim",
            "berg",
            "burg",
            "holt",
            "feld",
            "stein",
            "fjord",
            "mere",
            "vale"
        ],
        maxConsRun: 3,
        maxVowelRun: 2,
        minVowelRatio: 0.25,
        treatYAsVowel: true,
        minSyllables: 2,
        maxSyllables: 5,
        clusterLinker: "e",
        vowelLinker: "n"
    },
    "TURKIC": {
        onsets: [
            "al",
            "ar",
            "as",
            "at",
            "ba",
            "da",
            "ka",
            "qa",
            "kar",
            "gar",
            "sar",
            "dar",
            "tar",
            "kan",
            "khan",
            "nor",
            "mir",
            "gul",
            "nur",
            "shah",
            "bek",
            "han",
            "tur",
            "oglu",
            "akh"
        ],
        vowels: [
            "a",
            "e",
            "i",
            "o",
            "u",
            "ı",
            "ö",
            "ü",
            "ai",
            "ia",
            "ua",
            "ui"
        ],
        codas: [
            "n",
            "m",
            "r",
            "s",
            "sh",
            "z",
            "k",
            "g",
            "l"
        ],
        codaChance: 0.5,
        medials: [
            "abad",
            "stan",
            "sar",
            "mir",
            "dar",
            "koy",
            "kent",
            "han",
            "oglu"
        ],
        medialMorphChance: 0.45,
        suffixes: [
            "stan",
            "istan",
            "abad",
            "koy",
            "kent",
            "han"
        ],
        maxConsRun: 2,
        maxVowelRun: 3,
        minVowelRatio: 0.33,
        treatYAsVowel: false,
        minSyllables: 2,
        maxSyllables: 5,
        clusterLinker: "i",
        vowelLinker: "y"
    },
    "SEMITIC": {
        onsets: [
            "al",
            "ar",
            "as",
            "bal",
            "dar",
            "qal",
            "mal",
            "ram",
            "sam",
            "zar",
            "bar",
            "sar",
            "ham",
            "has",
            "kar",
            "lam",
            "nah",
            "tas",
            "rah",
            "fa",
            "za"
        ],
        vowels: [...V_SEMI,
            "aa",
            "ai",
            "ei",
            "ia"
        ],
        codas: [
            "n",
            "m",
            "r",
            "l",
            "s",
            "h",
            "t",
            "d"
        ],
        codaChance: 0.55,
        medials: [
            "har",
            "sar",
            "ram",
            "bar",
            "rah",
            "nah",
            "far",
            "kal",
            "tal",
            "mir",
            "zah",
            "mar"
        ],
        medialMorphChance: 0.55,
        suffixes: [
            "ia",
            "aya",
            "iyya",
            "ah",
            "an",
            "un",
            "iel",
            "em",
            "een"
        ],
        maxConsRun: 2,
        maxVowelRun: 3,
        minVowelRatio: 0.32,
        treatYAsVowel: false,
        minSyllables: 2,
        maxSyllables: 5,
        clusterLinker: "a",
        vowelLinker: "y"
    },
    "BANTU_LIKE": {
        onsets: [
            "ba",
            "ka",
            "ma",
            "na",
            "sa",
            "la",
            "ga",
            "pa",
            "ra",
            "cha",
            "tsa",
            "kwa",
            "gwa",
            "mwa",
            "nla",
            "mba",
            "nda",
            "nga",
            "ha"
        ],
        vowels: [
            "a",
            "e",
            "i",
            "o",
            "u",
            "a",
            "a",
            "i",
            "o",
            "u"
        ],
        codas: [
            ""
        ],
        codaChance: 0.05,
        medials: [
            "na",
            "ma",
            "ka",
            "ra",
            "ba",
            "la"
        ],
        medialMorphChance: 0.25,
        suffixes: [
            "ia",
            "ana",
            "uma",
            "ela",
            "olo"
        ],
        maxConsRun: 1,
        maxVowelRun: 4,
        minVowelRatio: 0.5,
        treatYAsVowel: true,
        minSyllables: 2,
        maxSyllables: 6,
        clusterLinker: "",
        vowelLinker: "n"
    },
    "AFRICAN_WEST": {
        onsets: [
            "a",
            "ba",
            "da",
            "ka",
            "fa",
            "ga",
            "la",
            "ma",
            "na",
            "oba",
            "ola",
            "ade",
            "kw",
            "gb",
            "ch",
            "ny",
            "eke",
            "ife",
            "olu",
            "ayo",
            "tunde",
            "chi",
            "obi"
        ],
        vowels: [
            "a",
            "e",
            "i",
            "o",
            "u",
            "ai",
            "oa",
            "ie",
            "ua",
            "aa",
            "ei"
        ],
        codas: [
            "n",
            "m",
            "wa",
            "ra",
            "ya",
            "ba",
            "",
            "do"
        ],
        codaChance: 0.4,
        medials: [
            "loba",
            "femi",
            "kwe",
            "tunde",
            "chukwu",
            "nwa",
            "kofi",
            "yemi",
            "sade",
            "dapo",
            "bisi",
            "tola",
            "ayo",
            "seun"
        ],
        medialMorphChance: 0.5,
        suffixes: [
            "la",
            "ba",
            "ra",
            "ni",
            "do",
            "ma",
            "si",
            "ye",
            "wa",
            "le"
        ],
        maxConsRun: 2,
        maxVowelRun: 4,
        minVowelRatio: 0.45,
        treatYAsVowel: true,
        minSyllables: 2,
        maxSyllables: 6,
        clusterLinker: "a",
        vowelLinker: "n"
    },
    "AFRICAN_HORN": {
        onsets: [
            "ab",
            "ad",
            "as",
            "ba",
            "da",
            "ha",
            "ka",
            "ma",
            "na",
            "sa",
            "ra",
            "ta",
            "gez",
            "tes",
            "hab",
            "sel",
            "mer",
            "zer",
            "yon",
            "lem",
            "kid",
            "sen",
            "tek",
            "geb",
            "yor"
        ],
        vowels: [
            "a",
            "e",
            "i",
            "o",
            "u",
            "aa",
            "ee",
            "ei",
            "ia",
            "ua",
            "io"
        ],
        codas: [
            "s",
            "m",
            "n",
            "l",
            "t",
            "k",
            "r",
            "",
            "h"
        ],
        codaChance: 0.5,
        medials: [
            "sel",
            "geb",
            "tek",
            "yon",
            "hab",
            "mar",
            "zer",
            "wold",
            "yas",
            "lem",
            "kid",
            "ber",
            "sen",
            "hak"
        ],
        medialMorphChance: 0.55,
        suffixes: [
            "el",
            "es",
            "os",
            "on",
            "u",
            "en",
            "em",
            "et",
            "ah"
        ],
        maxConsRun: 2,
        maxVowelRun: 3,
        minVowelRatio: 0.4,
        treatYAsVowel: true,
        minSyllables: 2,
        maxSyllables: 6,
        clusterLinker: "e",
        vowelLinker: "n"
    },
    "CN": {
        onsets: [
            "b",
            "p",
            "m",
            "f",
            "d",
            "t",
            "n",
            "l",
            "g",
            "k",
            "h",
            "zh",
            "ch",
            "sh",
            "r",
            "z",
            "c",
            "s",
            "j",
            "q",
            "x",
            "y",
            "w",
            "gu",
            "ku",
            "hu",
            "lu",
            "mu",
            "xi",
            "liang",
            "long"
        ],
        vowels: [
            "a",
            "o",
            "e",
            "i",
            "u",
            "ü",
            "ai",
            "ei",
            "ao",
            "ou",
            "ia",
            "ie",
            "iao",
            "iu",
            "ua",
            "uo",
            "ui",
            "üe",
            "er",
            "an",
            "ang",
            "en",
            "eng",
            "ong"
        ],
        codas: [
            "n",
            "ng",
            "",
            "r"
        ],
        codaChance: 0.45,
        medials: [
            "shan",
            "jiang",
            "he",
            "hu",
            "zhou",
            "dao",
            "lin",
            "yang",
            "qing",
            "jing",
            "guo",
            "cheng",
            "hai",
            "feng",
            "liang",
            "hua",
            "long",
            "yun",
            "xing",
            "mei",
            "xi",
            "tai",
            "hong",
            "lan",
            "tian",
            "bao"
        ],
        medialMorphChance: 0.4,
        suffixes: [
            "shan",
            "dao",
            "zhou",
            "guo",
            "cheng",
            "men",
            "hai",
            "yuan",
            "jing",
            "tan",
            "he",
            "lin",
            "feng",
            "yun",
            "xiang"
        ],
        maxConsRun: 2,
        maxVowelRun: 3,
        minVowelRatio: 0.3,
        treatYAsVowel: false,
        minSyllables: 2,
        maxSyllables: 5,
        clusterLinker: "e",
        vowelLinker: "n"
    },
    "JP": {
        onsets: [
            "k",
            "s",
            "t",
            "n",
            "h",
            "m",
            "y",
            "r",
            "w",
            "g",
            "z",
            "d",
            "b",
            "p",
            "ky",
            "sh",
            "ch",
            "ny",
            "hy",
            "my",
            "ry",
            "gy",
            "j",
            "py",
            "tak",
            "min",
            "har",
            "kaz",
            "yam",
            "mor",
            "sug",
            "tos",
            "ken",
            "rin",
            "aki",
            "yosh",
            "nao"
        ],
        vowels: [
            "a",
            "i",
            "u",
            "e",
            "o",
            "ai",
            "ou",
            "ei"
        ],
        codas: [
            "",
            "n"
        ],
        codaChance: 0.4,
        medials: [
            "mori",
            "yama",
            "kawa",
            "gawa",
            "shima",
            "jima",
            "saka",
            "hara",
            "tani",
            "naka",
            "oka",
            "zawa",
            "miya",
            "sugi",
            "tora",
            "fune",
            "nori",
            "kaze",
            "seki",
            "matsu",
            "hana",
            "take",
            "ishi",
            "sora",
            "minato",
            "arai",
            "kuni",
            "aki",
            "nobu",
            "hiko"
        ],
        medialMorphChance: 0.4,
        suffixes: [
            "to",
            "ken",
            "do",
            "fu",
            "shi",
            "mura",
            "saki",
            "hama",
            "gane",
            "no",
            "ya",
            "zaki",
            "moto",
            "dai",
            "zawa",
            "sawa",
            "gawa",
            "jima",
            "sei"
        ],
        maxConsRun: 2,
        maxVowelRun: 3,
        minVowelRatio: 0.35,
        treatYAsVowel: false,
        minSyllables: 2,
        maxSyllables: 5,
        clusterLinker: "u",
        vowelLinker: "n"
    },
    "POLYNESIAN": {
        onsets: [
            "",
            "h",
            "k",
            "l",
            "m",
            "n",
            "p",
            "r",
            "t",
            "w",
            "f",
            "v",
            "wh",
            "ng"
        ],
        vowels: [
            "a",
            "e",
            "i",
            "o",
            "u"
        ],
        codas: [
            "",
            "’",
            "ʻ"
        ],
        codaChance: 0.18,
        medials: [
            "moa",
            "moana",
            "rangi",
            "tonga",
            "tai",
            "wai",
            "puna",
            "tapu",
            "mana",
            "ariki",
            "tiki",
            "honu",
            "pua",
            "mata",
            "ika",
            "nui",
            "loa",
            "roa",
            "hale",
            "fale",
            "mauna",
            "nalu",
            "kai",
            "kea",
            "waiu",
            "pala",
            "koro"
        ],
        medialMorphChance: 0.38,
        suffixes: [
            "nui",
            "roa",
            "loa",
            "rangi",
            "moana",
            "tonga",
            "tai",
            "puna",
            "motu",
            "kai",
            "tahi",
            "ora",
            "kiri"
        ],
        maxConsRun: 1,
        maxVowelRun: 4,
        minVowelRatio: 0.5,
        treatYAsVowel: false,
        minSyllables: 2,
        maxSyllables: 6,
        clusterLinker: "",
        vowelLinker: "n"
    },
    "MONGOLIC": {
        onsets: [
            "ba",
            "bo",
            "bu",
            "ta",
            "to",
            "tu",
            "ga",
            "go",
            "gu",
            "da",
            "do",
            "du",
            "kha",
            "kh",
            "qa",
            "qar",
            "gur",
            "dar",
            "bor",
            "nar",
            "sar",
            "bat",
            "alt",
            "bogd",
            "sukh",
            "ul",
            "tur",
            "tor",
            "ur",
            "ar",
            "or"
        ],
        vowels: [
            "a",
            "e",
            "i",
            "o",
            "u",
            "aa",
            "ee",
            "ii",
            "oo",
            "uu",
            "ai",
            "oi",
            "ua"
        ],
        codas: [
            "n",
            "r",
            "g",
            "t",
            "s",
            "k",
            ""
        ],
        codaChance: 0.55,
        medials: [
            "bator",
            "baatar",
            "dorj",
            "suren",
            "erdene",
            "tungal",
            "bayar",
            "bold",
            "gan",
            "khaan",
            "ger",
            "gol",
            "dalai",
            "del",
            "uur",
            "saihan",
            "altai"
        ],
        medialMorphChance: 0.5,
        suffixes: [
            "bator",
            "baatar",
            "gur",
            "tengri",
            "dalai",
            "khaan",
            "khun",
            "gol",
            "ger"
        ],
        maxConsRun: 2,
        maxVowelRun: 2,
        minVowelRatio: 0.34,
        treatYAsVowel: false,
        minSyllables: 2,
        maxSyllables: 6,
        clusterLinker: "e",
        vowelLinker: "n"
    },
    "GREEKIC": {
        onsets: [
            "a",
            "e",
            "i",
            "o",
            "u",
            "k",
            "p",
            "t",
            "n",
            "m",
            "l",
            "r",
            "s",
            "d",
            "b",
            "g",
            "x",
            "ch",
            "ph",
            "th",
            "ps",
            "kr",
            "br",
            "tr"
        ],
        vowels: [
            "a",
            "e",
            "i",
            "o",
            "u",
            "ai",
            "ei",
            "oi",
            "ou",
            "au",
            "ia",
            "io"
        ],
        codas: [
            "s",
            "n",
            "r",
            "m",
            "l",
            "os",
            "on",
            "as",
            "is"
        ],
        codaChance: 0.55,
        medials: [
            "polis",
            "agora",
            "acro",
            "therm",
            "geo",
            "philo",
            "neo",
            "arch",
            "dora",
            "kastro",
            "nik",
            "dios"
        ],
        medialMorphChance: 0.45,
        suffixes: [
            "os",
            "on",
            "ia",
            "is",
            "as",
            "ikon",
            "ides"
        ],
        maxConsRun: 2,
        maxVowelRun: 2,
        minVowelRatio: 0.33,
        treatYAsVowel: false,
        minSyllables: 2,
        maxSyllables: 5,
        clusterLinker: "o",
        vowelLinker: "n"
    },
    "RUSSIANIC": {
        onsets: [
            "b",
            "v",
            "g",
            "d",
            "z",
            "k",
            "l",
            "m",
            "n",
            "p",
            "r",
            "s",
            "t",
            "br",
            "bl",
            "kr",
            "kl",
            "pr",
            "pl",
            "gr",
            "gl",
            "dr",
            "dl",
            "st",
            "sk",
            "str",
            "sl",
            "sm",
            "sn",
            "zh",
            "ch",
            "sh",
            "ts",
            "tz",
            "tr"
        ],
        vowels: [
            "a",
            "e",
            "i",
            "o",
            "u",
            "ya",
            "yo",
            "yu",
            "ia",
            "ie",
            "io",
            "oi"
        ],
        codas: [
            "v",
            "n",
            "r",
            "sk",
            "st",
            "ch",
            "sh",
            "k",
            "vich",
            "nik",
            "nov",
            "mir",
            "gor",
            "grad",
            "lin",
            "ev",
            "ov",
            "in",
            "en"
        ],
        codaChance: 0.75,
        medials: [
            "slav",
            "grad",
            "mir",
            "bor",
            "dov",
            "vol",
            "krav",
            "mirs",
            "krov",
            "bel",
            "ost",
            "tar",
            "grom",
            "step",
            "vel",
            "ser",
            "zar"
        ],
        medialMorphChance: 0.55,
        suffixes: [
            "ov",
            "in",
            "sky",
            "ska",
            "ovich",
            "ev",
            "enko",
            "grad",
            "mir",
            "ovka",
            "ovna",
            "aya"
        ],
        maxConsRun: 3,
        maxVowelRun: 2,
        minVowelRatio: 0.25,
        treatYAsVowel: false,
        minSyllables: 2,
        maxSyllables: 5,
        clusterLinker: "e",
        vowelLinker: "y"
    },
    "LATINIC": {
        onsets: [
            "a",
            "e",
            "i",
            "o",
            "u",
            "b",
            "c",
            "d",
            "f",
            "g",
            "l",
            "m",
            "n",
            "p",
            "r",
            "s",
            "t",
            "v",
            "cl",
            "fl",
            "gl",
            "pr",
            "tr",
            "cr",
            "pl",
            "fr",
            "gr",
            "dr",
            "qu",
            "sc",
            "sp",
            "st",
            "ct",
            "ph"
        ],
        vowels: [
            "a",
            "e",
            "i",
            "o",
            "u",
            "ae",
            "oe",
            "au",
            "ia",
            "io",
            "ua",
            "uo",
            "eu"
        ],
        codas: [
            "s",
            "n",
            "r",
            "m",
            "t",
            "l",
            "us",
            "um",
            "a",
            "is",
            "os"
        ],
        codaChance: 0.58,
        medials: [
            "dom",
            "val",
            "magn",
            "clar",
            "fort",
            "sanct",
            "imper",
            "aure",
            "vit",
            "cel",
            "luc",
            "reg",
            "mart",
            "pax",
            "bell",
            "civ",
            "jur",
            "templ",
            "script",
            "capit",
            "aug",
            "pont",
            "caes",
            "roman"
        ],
        medialMorphChance: 0.52,
        suffixes: [
            "us",
            "um",
            "a",
            "or",
            "is",
            "ianus",
            "ensis",
            "atus",
            "itas",
            "orium",
            "arium",
            "alis",
            "ivus",
            "itas"
        ],
        maxConsRun: 2,
        maxVowelRun: 3,
        minVowelRatio: 0.35,
        treatYAsVowel: true,
        minSyllables: 2,
        maxSyllables: 5,
        clusterLinker: "e",
        vowelLinker: "l"
    },
    "CELESTIC": {
        onsets: [
            "a",
            "ae",
            "e",
            "el",
            "al",
            "il",
            "ol",
            "ul",
            "cel",
            "ser",
            "ver",
            "lir",
            "aur",
            "eir",
            "mir",
            "thal",
            "val"
        ],
        vowels: [
            "a",
            "e",
            "i",
            "o",
            "u",
            "ae",
            "ea",
            "ai",
            "ia",
            "ie",
            "io",
            "ou",
            "ui"
        ],
        codas: [
            "l",
            "n",
            "r",
            "s",
            "th",
            "el",
            "iel",
            "ar",
            "is",
            "as"
        ],
        codaChance: 0.55,
        medials: [
            "ael",
            "iel",
            "ion",
            "ora",
            "iel",
            "ir",
            "ara",
            "uri",
            "arion"
        ],
        medialMorphChance: 0.6,
        suffixes: [
            "iel",
            "ael",
            "ion",
            "ora",
            "is",
            "arion",
            "iel",
            "eth"
        ],
        maxConsRun: 2,
        maxVowelRun: 2,
        minVowelRatio: 0.4,
        treatYAsVowel: true,
        minSyllables: 2,
        maxSyllables: 5,
        clusterLinker: "e",
        vowelLinker: "r"
    },
    "INFERNIC": {
        onsets: [
            "gr",
            "kr",
            "dr",
            "br",
            "thr",
            "vr",
            "zr",
            "kl",
            "sk",
            "sn",
            "gn",
            "vrog",
            "ulg",
            "zor",
            "rak",
            "gash",
            "morg"
        ],
        vowels: [
            "a",
            "o",
            "u",
            "e",
            "ia",
            "oa",
            "ua",
            "ai",
            "oi"
        ],
        codas: [
            "th",
            "k",
            "g",
            "r",
            "z",
            "x",
            "sh",
            "kh",
            "gh",
            "n",
            "m"
        ],
        codaChance: 0.75,
        medials: [
            "gor",
            "zul",
            "rak",
            "thr",
            "khar",
            "vur",
            "drak",
            "mor",
            "gron",
            "vul"
        ],
        medialMorphChance: 0.45,
        suffixes: [
            "oth",
            "ar",
            "rak",
            "gul",
            "zor",
            "eth",
            "uzad",
            "ash",
            "ath"
        ],
        maxConsRun: 4,
        maxVowelRun: 4,
        minVowelRatio: 0.2,
        treatYAsVowel: false,
        minSyllables: 2,
        maxSyllables: 5,
        clusterLinker: "a",
        vowelLinker: "r"
    },
    "ARCANE": {
        onsets: [
            "a",
            "e",
            "i",
            "o",
            "u",
            "x",
            "z",
            "v",
            "q",
            "k",
            "s",
            "r",
            "th",
            "sh",
            "ch",
            "ph",
            "gh",
            "xa",
            "xi",
            "ze",
            "zy",
            "qu",
            "ka",
            "ly",
            "sy",
            "va",
            "or",
            "ny"
        ],
        vowels: [
            "a",
            "e",
            "i",
            "o",
            "u",
            "ae",
            "ia",
            "ie",
            "io",
            "ei",
            "ou",
            "ui"
        ],
        codas: [
            "n",
            "r",
            "s",
            "th",
            "x",
            "z",
            "sh",
            "m",
            "l",
            "t"
        ],
        codaChance: 0.6,
        medials: [
            "ar",
            "en",
            "is",
            "os",
            "ith",
            "al",
            "or",
            "ir",
            "um",
            "ex",
            "ul"
        ],
        medialMorphChance: 0.5,
        suffixes: [
            "ar",
            "en",
            "is",
            "os",
            "ith",
            "or",
            "ul",
            "um",
            "ae",
            "ion"
        ],
        maxConsRun: 3,
        maxVowelRun: 3,
        minVowelRatio: 0.3,
        treatYAsVowel: true,
        minSyllables: 2,
        maxSyllables: 5,
        clusterLinker: "e",
        vowelLinker: "r"
    },
    "DEEP_SPEECH": {
        onsets: [
            "gh",
            "gr",
            "kr",
            "zr",
            "zh",
            "xh",
            "kl",
            "ql",
            "k’",
            "x’",
            "t’",
            "sh",
            "sk",
            "thl",
            "vr",
            "vx",
            "dl",
            "rk"
        ],
        vowels: [
            "a",
            "u",
            "o",
            "e",
            "ia",
            "ua",
            "ao",
            "ou",
            ""
        ],
        codas: [
            "th",
            "x",
            "g",
            "k",
            "z",
            "sh",
            "’th",
            "’x",
            "’g",
            "n"
        ],
        codaChance: 0.8,
        medials: [
            "ul",
            "gur",
            "zha",
            "kth",
            "rax",
            "xul",
            "gath",
            "urh",
            "shul",
            "vrax",
            "qor",
            "thrul",
            "zoth"
        ],
        medialMorphChance: 0.45,
        suffixes: [
            "’thul",
            "’gath",
            "’nax",
            "’ul",
            "’rax",
            "oth",
            "zoth",
            "gath",
            "khul"
        ],
        maxConsRun: 4,
        maxVowelRun: 4,
        minVowelRatio: 0.2,
        treatYAsVowel: false,
        minSyllables: 2,
        maxSyllables: 5,
        clusterLinker: "’",
        vowelLinker: "h"
    },
    "GOBLINIC": {
        onsets: [
            "g",
            "gr",
            "kr",
            "kl",
            "sn",
            "sk",
            "sm",
            "sp",
            "st",
            "tr",
            "dr",
            "bl",
            "br",
            "pl",
            "gl",
            "zz",
            "gn",
            "ch",
            "sc"
        ],
        vowels: [
            "a",
            "e",
            "i",
            "o",
            "u",
            "aa",
            "oo",
            "ei",
            "oi"
        ],
        codas: [
            "k",
            "g",
            "n",
            "m",
            "b",
            "t",
            "z",
            "zz",
            "sh",
            "p",
            "x",
            ""
        ],
        codaChance: 0.7,
        medials: [
            "grub",
            "snag",
            "krat",
            "blit",
            "skrag",
            "drub",
            "gnar",
            "plok",
            "zib",
            "krin",
            "grot",
            "snib"
        ],
        medialMorphChance: 0.45,
        suffixes: [
            "ak",
            "ig",
            "ok",
            "nob",
            "zit",
            "gob",
            "bag",
            "pik",
            "nip",
            "ogg"
        ],
        maxConsRun: 3,
        maxVowelRun: 3,
        minVowelRatio: 0.28,
        treatYAsVowel: false,
        minSyllables: 2,
        maxSyllables: 5,
        clusterLinker: "i",
        vowelLinker: "g"
    },
    "TECHNARCH": {
        onsets: [
            "auto",
            "mecha",
            "syn",
            "alg",
            "dat",
            "net",
            "cyb",
            "neuro",
            "quant",
            "proto",
            "nano",
            "vector",
            "core",
            "node",
            "grid",
            "flux",
            "servo"
        ],
        vowels: [
            "a",
            "e",
            "i",
            "o",
            "u",
            "ai",
            "io",
            "ea",
            "ou",
            "ui"
        ],
        codas: [
            "on",
            "ix",
            "ex",
            "um",
            "is",
            "os",
            "",
            "core"
        ],
        codaChance: 0.6,
        medials: [
            "tron",
            "link",
            "proc",
            "calc",
            "mach",
            "net",
            "bot",
            "loop",
            "core",
            "data"
        ],
        medialMorphChance: 0.5,
        suffixes: [
            "on",
            "ix",
            "ex",
            "ium",
            "aris",
            "logicus",
            "tek",
            "sys"
        ],
        maxConsRun: 3,
        maxVowelRun: 3,
        minVowelRatio: 0.3,
        treatYAsVowel: true,
        minSyllables: 2,
        maxSyllables: 6,
        clusterLinker: "e",
        vowelLinker: "l"
    },
    "FUEGIC": {
        onsets: [
            "f",
            "ph",
            "b",
            "v",
            "p",
            "t",
            "th",
            "kh",
            "k",
            "r",
            "s",
            "sh",
            "ch",
            "z",
            "br",
            "kr",
            "fr",
            "fl",
            "dr",
            "gr",
            "vr",
            "zar",
            "bal",
            "kal",
            "ash",
            "rav",
            "ign",
            "py",
            "flam"
        ],
        vowels: [
            "a",
            "e",
            "i",
            "o",
            "u",
            "aa",
            "ae",
            "ai",
            "au",
            "ea",
            "ei",
            "io",
            "oa",
            "ou",
            "ua"
        ],
        codas: [
            "r",
            "s",
            "th",
            "x",
            "z",
            "n",
            "m",
            "sh",
            "ch",
            "k",
            "t",
            "ar",
            "az",
            "eth",
            "oth"
        ],
        codaChance: 0.7,
        medials: [
            "ash",
            "zar",
            "rak",
            "vyr",
            "thar",
            "gor",
            "ign",
            "az",
            "flar",
            "kesh",
            "rath",
            "vor",
            "pyra"
        ],
        medialMorphChance: 0.45,
        suffixes: [
            "ash",
            "ur",
            "zar",
            "eth",
            "or",
            "oth",
            "ar",
            "rak",
            "ath",
            "zor",
            "ion"
        ],
        maxConsRun: 3,
        maxVowelRun: 2,
        minVowelRatio: 0.22,
        treatYAsVowel: false,
        minSyllables: 2,
        maxSyllables: 6,
        clusterLinker: "a",
        vowelLinker: "r"
    },
    "SIRENIC": {
        onsets: [
            "a",
            "e",
            "i",
            "o",
            "u",
            "l",
            "n",
            "m",
            "s",
            "v",
            "r",
            "h",
            "w",
            "sh",
            "th",
            "ph",
            "ch",
            "wh",
            "ly",
            "ny",
            "sel",
            "sir",
            "mar",
            "nai",
            "ora",
            "thal",
            "vel",
            "mel",
            "lun",
            "aqu",
            "ond"
        ],
        vowels: [
            "a",
            "e",
            "i",
            "o",
            "u",
            "ae",
            "ai",
            "ea",
            "ee",
            "ia",
            "ie",
            "io",
            "oa",
            "oe",
            "ou",
            "ua",
            "ue",
            "ui"
        ],
        codas: [
            "n",
            "r",
            "l",
            "s",
            "th",
            "sh",
            "h",
            "m",
            "el",
            "en",
            "ir",
            "is",
            "a",
            "ia",
            "ine"
        ],
        codaChance: 0.45,
        medials: [
            "ara",
            "ela",
            "ine",
            "ora",
            "ula",
            "iri",
            "oni",
            "ari",
            "una",
            "esi",
            "mar",
            "sel",
            "vai",
            "wen",
            "lua",
            "nys"
        ],
        medialMorphChance: 0.4,
        suffixes: [
            "ine",
            "is",
            "ir",
            "iel",
            "ora",
            "ara",
            "una",
            "elle",
            "en",
            "ys",
            "eth",
            "wen"
        ],
        maxConsRun: 2,
        maxVowelRun: 4,
        minVowelRatio: 0.4,
        treatYAsVowel: true,
        minSyllables: 2,
        maxSyllables: 6,
        clusterLinker: "l",
        vowelLinker: "n"
    },
    "OOGA_BOOGA": {
        onsets: [
            "",
            "b",
            "g",
            "k",
            "m",
            "n",
            "t",
            "p",
            "w",
            "h",
            "bg",
            "gb",
            "gr",
            "kr"
        ],
        vowels: [
            "o",
            "a",
            "u",
            "oo",
            "oa",
            "ou",
            "ua",
            "uga",
            "oga"
        ],
        codas: [
            "",
            "g",
            "k",
            "ng",
            "ga",
            "ka",
            "gk"
        ],
        codaChance: 0.72,
        medials: [
            "ooga",
            "booga",
            "boga",
            "maka",
            "taka",
            "gora",
            "gugu",
            "koko",
            "boko"
        ],
        medialMorphChance: 0.35,
        suffixes: [
            "uga",
            "booga",
            "g",
            "ka",
            "ko",
            "ga",
            "bog",
            "ok"
        ],
        maxConsRun: 2,
        maxVowelRun: 4,
        minVowelRatio: 0.4,
        treatYAsVowel: false,
        minSyllables: 2,
        maxSyllables: 5,
        clusterLinker: "g",
        vowelLinker: "k"
    },
    "DWARVISH": {
        onsets: [
            "b",
            "d",
            "g",
            "k",
            "m",
            "n",
            "r",
            "t",
            "v",
            "z",
            "br",
            "dr",
            "gr",
            "kr",
            "tr",
            "thr",
            "kh"
        ],
        vowels: [
            "a",
            "e",
            "i",
            "o",
            "u",
            "ai",
            "oi",
            "au"
        ],
        codas: [
            "r",
            "n",
            "m",
            "k",
            "g",
            "d",
            "nd",
            "rd",
            "ld",
            "rn",
            "rm",
            "rg",
            "rk"
        ],
        codaChance: 0.75,
        medials: [
            "dur",
            "grim",
            "bar",
            "kar",
            "grom",
            "thal",
            "dun",
            "fund",
            "brak",
            "stenn",
            "stein"
        ],
        medialMorphChance: 0.45,
        suffixes: [
            "in",
            "ar",
            "orn",
            "grin",
            "dun",
            "hald",
            "heim",
            "hold"
        ],
        maxConsRun: 3,
        maxVowelRun: 3,
        minVowelRatio: 0.28,
        treatYAsVowel: false,
        minSyllables: 2,
        maxSyllables: 5,
        clusterLinker: "e",
        vowelLinker: "r"
    },
    "HALFLING": {
        onsets: [
            "b",
            "d",
            "f",
            "g",
            "h",
            "j",
            "k",
            "l",
            "m",
            "n",
            "p",
            "r",
            "s",
            "t",
            "w",
            "br",
            "cl",
            "fl",
            "pl",
            "wh"
        ],
        vowels: [
            "a",
            "e",
            "i",
            "o",
            "u",
            "ie",
            "ea",
            "ai",
            "oa",
            "oi",
            "oo"
        ],
        codas: [
            "n",
            "r",
            "l",
            "m",
            "s",
            "t",
            "ck",
            "nd",
            "rt",
            "ft",
            "ley",
            "ton"
        ],
        codaChance: 0.55,
        medials: [
            "apple",
            "bur",
            "brook",
            "dale",
            "mill",
            "merry",
            "will",
            "hedge",
            "bottle",
            "puddle"
        ],
        medialMorphChance: 0.3,
        suffixes: [
            "ton",
            "ford",
            "wick",
            "brook",
            "hill",
            "bury",
            "shaw",
            "combe",
            "ley"
        ],
        maxConsRun: 2,
        maxVowelRun: 3,
        minVowelRatio: 0.35,
        treatYAsVowel: true,
        minSyllables: 2,
        maxSyllables: 5,
        clusterLinker: "e",
        vowelLinker: "l"
    },
    "NOCTURNIC": {
        onsets: [
            "v",
            "s",
            "z",
            "r",
            "l",
            "m",
            "n",
            "d",
            "t",
            "c",
            "ch",
            "sh",
            "vr",
            "cr",
            "dr",
            "str"
        ],
        vowels: [
            "a",
            "e",
            "i",
            "o",
            "u",
            "ae",
            "ei",
            "ia",
            "io",
            "ou",
            "ui"
        ],
        codas: [
            "r",
            "s",
            "th",
            "x",
            "z",
            "n",
            "l",
            "re",
            "is",
            "us",
            "oth",
            "yx"
        ],
        codaChance: 0.65,
        medials: [
            "nos",
            "sang",
            "vel",
            "mor",
            "car",
            "lac",
            "umbr",
            "noir",
            "vlad",
            "rav",
            "dusk"
        ],
        medialMorphChance: 0.45,
        suffixes: [
            "ius",
            "elle",
            "oire",
            "an",
            "ar",
            "or",
            "yx",
            "ath",
            "osa"
        ],
        maxConsRun: 3,
        maxVowelRun: 3,
        minVowelRatio: 0.3,
        treatYAsVowel: true,
        minSyllables: 2,
        maxSyllables: 6,
        clusterLinker: "e",
        vowelLinker: "r"
    },
    "DERPTONGUE": {
        onsets: [
            "b",
            "g",
            "k",
            "p",
            "d",
            "t",
            "f",
            "m",
            "n",
            "r",
            "s",
            "bl",
            "gr",
            "kr",
            "sn",
            "pl",
            "fl",
            "z",
            "v"
        ],
        vowels: [
            "a",
            "e",
            "i",
            "o",
            "u",
            "oo",
            "ee",
            "uh",
            "ah",
            "ow"
        ],
        codas: [
            "",
            "g",
            "k",
            "p",
            "t",
            "n",
            "m",
            "b",
            "sh",
            "zz",
            "rp",
            "nk"
        ],
        codaChance: 0.6,
        medials: [
            "derp",
            "blor",
            "snar",
            "plop",
            "gorp",
            "flub",
            "drool",
            "bonk",
            "boop"
        ],
        medialMorphChance: 0.55,
        suffixes: [
            "er",
            "us",
            "o",
            "ee",
            "oo",
            "ah",
            "uh",
            "boop",
            "onk"
        ],
        maxConsRun: 2,
        maxVowelRun: 4,
        minVowelRatio: 0.33,
        treatYAsVowel: true,
        minSyllables: 2,
        maxSyllables: 6,
        clusterLinker: "e",
        vowelLinker: "p"
    },
    "TOADISH": {
        onsets: [
            "gr",
            "kr",
            "br",
            "cro",
            "fro",
            "gl",
            "pl",
            "r",
            "bl",
            "cr",
            "tr",
            "dr"
        ],
        vowels: [
            "o",
            "u",
            "oo",
            "oa",
            "ou",
            "uh",
            "a",
            "ua"
        ],
        codas: [
            "g",
            "k",
            "rk",
            "rg",
            "mp",
            "b",
            "bb",
            "gk",
            "nk",
            "rr",
            "p"
        ],
        codaChance: 0.75,
        medials: [
            "croa",
            "rib",
            "grub",
            "glo",
            "slop",
            "murk",
            "drib",
            "blob"
        ],
        medialMorphChance: 0.45,
        suffixes: [
            "og",
            "ug",
            "ump",
            "ok",
            "ogg",
            "onk",
            "croak"
        ],
        maxConsRun: 3,
        maxVowelRun: 3,
        minVowelRatio: 0.28,
        treatYAsVowel: false,
        minSyllables: 2,
        maxSyllables: 5,
        clusterLinker: "r",
        vowelLinker: "g"
    },
    "BANANAIC": {
        onsets: [
            "",
            "b",
            "d",
            "g",
            "k",
            "m",
            "n",
            "p",
            "t",
            "w",
            "h",
            "ba",
            "na",
            "ma",
            "pa",
            "ga",
            "da"
        ],
        vowels: [
            "a",
            "e",
            "i",
            "o",
            "u",
            "aa",
            "ee",
            "oo",
            "ai",
            "au"
        ],
        codas: [
            "",
            "na",
            "ma",
            "pa",
            "ba",
            "ga",
            "ka",
            "la",
            "ha"
        ],
        codaChance: 0.6,
        medials: [
            "na",
            "nana",
            "mama",
            "papa",
            "gaga",
            "lala",
            "haha",
            "wawa",
            "baba",
            "dada"
        ],
        medialMorphChance: 0.6,
        suffixes: [
            "na",
            "nana",
            "banana",
            "mana",
            "pana",
            "bana",
            "lala",
            "haha"
        ],
        maxConsRun: 1,
        maxVowelRun: 4,
        minVowelRatio: 0.5,
        treatYAsVowel: true,
        minSyllables: 2,
        maxSyllables: 6,
        clusterLinker: "",
        vowelLinker: "n"
    },
    "LYRICIAN": {
        onsets: [
            "a",
            "e",
            "i",
            "o",
            "u",
            "l",
            "n",
            "m",
            "r",
            "s",
            "v",
            "f",
            "h",
            "y",
            "al",
            "el",
            "il",
            "ol",
            "ul",
            "ar",
            "en",
            "ir",
            "or",
            "ur",
            "ly",
            "ny",
            "th",
            "ph"
        ],
        vowels: [
            "a",
            "e",
            "i",
            "o",
            "u",
            "ai",
            "ei",
            "ia",
            "io",
            "oa",
            "ue",
            "ui"
        ],
        codas: [
            "l",
            "n",
            "r",
            "s",
            "th",
            "m",
            "el",
            "en",
            "ir",
            "is",
            "ar",
            "al"
        ],
        codaChance: 0.45,
        medials: [
            "ara",
            "eli",
            "ian",
            "ora",
            "ina",
            "ira",
            "ala",
            "esi",
            "len",
            "mir",
            "var",
            "ser",
            "vel",
            "lin"
        ],
        medialMorphChance: 0.35,
        suffixes: [
            "iel",
            "is",
            "en",
            "el",
            "ora",
            "ine",
            "ar",
            "eth",
            "iel",
            "ane"
        ],
        maxConsRun: 2,
        maxVowelRun: 4,
        minVowelRatio: 0.4,
        treatYAsVowel: true,
        minSyllables: 2,
        maxSyllables: 6,
        clusterLinker: "e",
        vowelLinker: "l"
    },
    "ANGLISHIC": {
        onsets: [
            "b",
            "br",
            "bl",
            "c",
            "cl",
            "cr",
            "d",
            "dr",
            "f",
            "fl",
            "fr",
            "g",
            "gr",
            "gl",
            "h",
            "j",
            "k",
            "kr",
            "l",
            "m",
            "n",
            "p",
            "pl",
            "pr",
            "r",
            "s",
            "sl",
            "sm",
            "sn",
            "sp",
            "st",
            "sw",
            "t",
            "tr",
            "v",
            "w",
            "wh"
        ],
        vowels: [
            "a",
            "e",
            "i",
            "o",
            "u",
            "ai",
            "ea",
            "ie",
            "oa",
            "oo",
            "ou",
            "uh",
            "ar",
            "er"
        ],
        codas: [
            "b",
            "d",
            "f",
            "g",
            "k",
            "l",
            "m",
            "n",
            "p",
            "r",
            "s",
            "t",
            "ck",
            "nd",
            "nt",
            "st",
            "sp",
            "sh",
            "th",
            "rd",
            "rk",
            "rm",
            "rl",
            "lp",
            "ft"
        ],
        codaChance: 0.6,
        medials: [
            "ing",
            "ish",
            "est",
            "ard",
            "orn",
            "all",
            "and",
            "ell",
            "ock",
            "ump",
            "old",
            "ent",
            "ram",
            "win",
            "ber",
            "ble",
            "trum",
            "croft",
            "shire",
            "worth"
        ],
        medialMorphChance: 0.4,
        suffixes: [
            "ton",
            "ham",
            "worth",
            "wick",
            "well",
            "ford",
            "croft",
            "den",
            "fell",
            "bury",
            "brook",
            "mere",
            "stead"
        ],
        maxConsRun: 3,
        maxVowelRun: 3,
        minVowelRatio: 0.3,
        treatYAsVowel: true,
        minSyllables: 2,
        maxSyllables: 6,
        clusterLinker: "e",
        vowelLinker: "r"
    },
    "NEW_ANGLISHIC": {
        onsets: [
            "a",
            "b",
            "br",
            "c",
            "cl",
            "cr",
            "d",
            "f",
            "fl",
            "fr",
            "g",
            "gl",
            "gr",
            "h",
            "j",
            "k",
            "kr",
            "l",
            "m",
            "n",
            "p",
            "pl",
            "pr",
            "r",
            "s",
            "sl",
            "sm",
            "sp",
            "st",
            "t",
            "tr",
            "v",
            "w",
            "well",
            "brook",
            "grove",
            "nex",
            "ever",
            "fair",
            "north",
            "east",
            "west",
            "green",
            "bright",
            "clear",
            "sil",
            "blue",
            "gold"
        ],
        vowels: [
            "a",
            "e",
            "i",
            "o",
            "u",
            "ai",
            "ea",
            "ie",
            "oa",
            "ou",
            "ar",
            "er",
            "or"
        ],
        codas: [
            "n",
            "r",
            "s",
            "t",
            "m",
            "l",
            "d",
            "k",
            "x",
            "nd",
            "nt",
            "rd",
            "rn",
            "st",
            "ft",
            "den",
            "ton",
            "ford",
            "ly"
        ],
        codaChance: 0.5,
        medials: [
            "well",
            "brook",
            "vale",
            "fold",
            "ridge",
            "moor",
            "bank",
            "port",
            "field",
            "mill",
            "crest",
            "grove",
            "point",
            "gate",
            "worth",
            "ford",
            "haven",
            "side",
            "wick",
            "holt",
            "mark"
        ],
        medialMorphChance: 0.4,
        suffixes: [
            "well",
            "fold",
            "worth",
            "ridge",
            "vale",
            "hill",
            "gate",
            "point",
            "mill",
            "brook",
            "haven",
            "croft",
            "grove",
            "port",
            "ly",
            "ton",
            "den",
            "sy",
            "corp",
            "soft",
            "tek"
        ],
        maxConsRun: 3,
        maxVowelRun: 3,
        minVowelRatio: 0.3,
        treatYAsVowel: true,
        minSyllables: 2,
        maxSyllables: 6,
        clusterLinker: "e",
        vowelLinker: "r"
    },
    "PHRASIC": {
        onsets: [
            "valley",
            "mount",
            "lake",
            "bay",
            "forest",
            "plain",
            "temple",
            "swamp",
            "fort",
            "isle",
            "village",
            "kingdom",
            "road",
            "castle",
            "hill",
            "river",
            "tunnel",
            "mine",
            "ruins",
            "shore",
            "field",
            "house",
            "well",
            "pit",
            "crater",
            "colony",
            "camp",
            "keep",
            "market",
            "bog"
        ],
        vowels: [
            " of ",
            " under ",
            " beyond ",
            " near ",
            " within ",
            " between ",
            " amidst ",
            " atop ",
            " behind ",
            " from "
        ],
        codas: [
            "the crying moon ",
            "the endless soup ",
            "the big chair ",
            "the sleepy frog ",
            "forgotten beans ",
            "the ninth duck ",
            "the friendly ghost ",
            "too many doors ",
            "a froggy pond ",
            "a dank cave ",
            "cheese regrets ",
            "goblin tickling ceremony ",
            "the once and future cat ",
            "the graves of your ancestors ",
            "questionable wifi ",
            "unseen noodles ",
            "the echoing pickle ",
            "the eternal goose ",
            "a thundering herd of mice ",
            "a village of cannibals ",
            "the world's largest sandcastle "
        ],
        codaChance: 1.0,
        medials: [
            "tiny ",
            "great ",
            "cursed ",
            "depressed ",
            "loud ",
            "pleasantly moist ",
            "haunted ",
            "confused ",
            "excessive ",
            "moderately holy ",
            "regrettable ",
            "dreadful ",
            "friendly "
        ],
        medialMorphChance: 0.5,
        suffixes: [
            " province",
            " territory",
            " realm",
            " domain",
            " nation",
            " municipality",
            " park",
            " zone",
            " collective",
            " area",
            " circle",
            " quarter",
            " complex",
            " region",
            " resort",
            " sanctuary"
        ],
        maxConsRun: 1_000,
        maxVowelRun: 1_000,
        minVowelRatio: 0,
        treatYAsVowel: true,
        minSyllables: 2,
        maxSyllables: 10,
        clusterLinker: "",
        vowelLinker: ""
    },
};
